package com.chinamobo.ue.system.dao;

import com.chinamobo.ue.system.entity.TomApiUser;

public interface TomApiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    int insert(TomApiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    int insertSelective(TomApiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    TomApiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    int updateByPrimaryKeySelective(TomApiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_API_USER
     *
     * @mbggenerated Wed Mar 23 13:31:57 CST 2016
     */
    int updateByPrimaryKey(TomApiUser record);
    
    TomApiUser selectByToken(String token);
}