package com.chinamobo.ue.system.dao;

import java.util.List;

import com.chinamobo.ue.system.entity.TomAuthoritiesType;

public interface TomAuthoritiesTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer authorityTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    int insert(TomAuthoritiesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    int insertSelective(TomAuthoritiesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    TomAuthoritiesType selectByPrimaryKey(Integer authorityTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomAuthoritiesType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_AUTHORITIES_TYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomAuthoritiesType record);
    
    List<TomAuthoritiesType> selectAllType();
    
    List<TomAuthoritiesType> selectByRoleId (int roleId);

	List<TomAuthoritiesType> selectAuthoritiesByRoilId(Integer roleId);

	List<TomAuthoritiesType> findAll();
}