package com.chinamobo.ue.system.dao;

import com.chinamobo.ue.system.entity.TomAppErrorLog;

public interface TomAppErrorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer errorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    int insert(TomAppErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    int insertSelective(TomAppErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    TomAppErrorLog selectByPrimaryKey(Integer errorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomAppErrorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_APP_ERROR_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomAppErrorLog record);
}