package com.chinamobo.ue.system.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.system.entity.TomActiveUser;

public interface TomActiveUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVE_USER
     *
     * @mbggenerated
     */
    int insert(TomActiveUser record);
    
    int update(TomActiveUser record);
    
    int delete(int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVE_USER
     *
     * @mbggenerated
     */
    int insertSelective(TomActiveUser record);
    
    List<TomActiveUser> select(Map<Object, Object> map);

    /**
     * 
     * 功能描述：[查询活跃用户]
     *
     * 创建者：JCX
     * 创建时间: 2016年7月14日 下午3:29:16
     * @param map
     * @return
     */
	int countActiveUsers(Map<Object, Object> map);
	//统计登录次数
	int countLoadTimes(Map<Object, Object> map);
	int countLoadTimesH5(Map<Object, Object> map);
}