package com.chinamobo.ue.system.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.system.entity.TomMessagesEmployees;

public interface TomMessagesEmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGE_EMPLOYEES
     *
     * @mbggenerated
     */
    int insert(TomMessagesEmployees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGE_EMPLOYEES
     *
     * @mbggenerated
     */
    int insertSelective(TomMessagesEmployees record);

    TomMessagesEmployees selectStatus(Map<Object, Object> map);

	void updateStatus(Map<Object, Object> map);


	
	List<TomMessagesEmployees> selectById(int messageId);
    
	int countByView(String userId); 
}