package com.chinamobo.ue.system.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.api.message.dto.MessageDto;
import com.chinamobo.ue.system.entity.TomMessages;

public interface TomMessagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    int insert(TomMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    int insertSelective(TomMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    TomMessages selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomMessages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_MESSAGES
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomMessages record);
    
    List<MessageDto>   selectByCode(Map<Object, Object> queryMap);

	int selectByCount(String code);
	
	int countByExample(Map<Object, Object> map1);

	List<TomMessages> selectByMany(Map<Object, Object> map);
}