package com.chinamobo.ue.system.dao;

import com.chinamobo.ue.system.entity.TomOperateLog;

public interface TomOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    int insert(TomOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    int insertSelective(TomOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    TomOperateLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_OPERATE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomOperateLog record);
}