package com.chinamobo.ue.system.dao;

import com.chinamobo.ue.system.entity.TomPostPraise;

public interface TomPostPraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_PRAISE
     *
     * @mbggenerated
     */
    int insert(TomPostPraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_POST_PRAISE
     *
     * @mbggenerated
     */
    int insertSelective(TomPostPraise record);
}