package com.chinamobo.ue.system.dao;

import java.util.List;

import com.chinamobo.ue.system.entity.TomRollingPictureRecord;

public interface TomRollingPictureRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ROLLING_PICTURE_RECORD
     *
     * @mbggenerated
     */
    int insert(TomRollingPictureRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ROLLING_PICTURE_RECORD
     *
     * @mbggenerated
     */
    int insertSelective(TomRollingPictureRecord record);

    /**
     * 
     * 功能描述：[查看记录数]
     *
     * 创建者：JCX
     * 创建时间: 2016年6月13日 上午10:23:48
     * @param rollingPictureRecord
     * @return
     */
	int countByExample(TomRollingPictureRecord rollingPictureRecord);

	List<TomRollingPictureRecord> selectById(int pictureId);
}