package com.chinamobo.ue.api.myInfo.dto;

import java.util.Date;

import javax.ws.rs.FormParam;

public class NewsDto {
	@FormParam("newsId")
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.NEWS_TITLE
     *
     * @mbggenerated
     */
    @FormParam("newsTitle")
    private String newsTitle;
    
    @FormParam("newsTitleEn")
    private String newsTitleEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.NEWS_PICTURE
     *
     * @mbggenerated
     */
    @FormParam("newsPicture")
    private String newsPicture;
    
    @FormParam("newsPictureEn")
    private String newsPictureEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.PK_ORG
     *
     * @mbggenerated
     */
    @FormParam("pkOrg")
    private String pkOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.RELEASE_TIME
     *
     * @mbggenerated
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.VIEW_COUNT
     *
     * @mbggenerated
     */
    @FormParam("viewCount")
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.IS_RELEASE
     *
     * @mbggenerated
     */
    @FormParam("isRelease")
    private String isRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.ADMINISTRATORS
     *
     * @mbggenerated
     */
    @FormParam("administrators")
    private String administrators;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.CREATER
     *
     * @mbggenerated
     */
    @FormParam("creater")
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.OPERATOR
     *
     * @mbggenerated
     */
    @FormParam("operator")
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NEWS.NEWS_DETAILS
     *
     * @mbggenerated
     */
    @FormParam("newsDetails")
    private String newsDetails;
    
    @FormParam("newsDetailsEn")
    private String newsDetailsEn;
    
    private String isView;

	public Integer getNewsId() {
		return newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	public String getNewsTitle() {
		return newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewsPicture() {
		return newsPicture;
	}

	public void setNewsPicture(String newsPicture) {
		this.newsPicture = newsPicture;
	}

	public String getPkOrg() {
		return pkOrg;
	}

	public void setPkOrg(String pkOrg) {
		this.pkOrg = pkOrg;
	}

	public Date getReleaseTime() {
		return releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	public Integer getViewCount() {
		return viewCount;
	}

	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	public String getIsRelease() {
		return isRelease;
	}

	public void setIsRelease(String isRelease) {
		this.isRelease = isRelease;
	}

	public String getAdministrators() {
		return administrators;
	}

	public void setAdministrators(String administrators) {
		this.administrators = administrators;
	}

	public String getCreater() {
		return creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getNewsDetails() {
		return newsDetails;
	}

	public void setNewsDetails(String newsDetails) {
		this.newsDetails = newsDetails;
	}

	public String getIsView() {
		return isView;
	}

	public void setIsView(String isView) {
		this.isView = isView;
	}

	public String getNewsTitleEn() {
		return newsTitleEn;
	}

	public void setNewsTitleEn(String newsTitleEn) {
		this.newsTitleEn = newsTitleEn;
	}

	public String getNewsDetailsEn() {
		return newsDetailsEn;
	}

	public void setNewsDetailsEn(String newsDetailsEn) {
		this.newsDetailsEn = newsDetailsEn;
	}

	public String getNewsPictureEn() {
		return newsPictureEn;
	}

	public void setNewsPictureEn(String newsPictureEn) {
		this.newsPictureEn = newsPictureEn;
	}
    
}
