package com.chinamobo.ue.activity.entity;

import java.util.Date;
import java.util.List;

import javax.ws.rs.FormParam;

import org.springframework.beans.factory.annotation.Autowired;

import com.chinamobo.ue.activity.common.DataEntity;
import com.chinamobo.ue.system.entity.TomEmp;
import com.chinamobo.ue.system.service.NumberRecordService;
import com.chinamobo.ue.ums.util.ShiroUtils;
import com.chinamobo.ue.utils.Global;
import com.chinamobo.ue.utils.MapManager;

public class TomActivity extends DataEntity<TomActivity>{
	
	private String imgpath;
	
	private String status;
	private Integer num;
	
	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	private Integer eB;
	
	private String finishStatus;
	
	private String code;
	
	@FormParam("isEN")
    private String isEN;
    @FormParam("isCN")
	private String isCN;
	
	public String getIsEN() {
		return isEN;
	}

	public void setIsEN(String isEN) {
		this.isEN = isEN;
	}

	public String getIsCN() {
		return isCN;
	}

	public void setIsCN(String isCN) {
		this.isCN = isCN;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Integer geteB() {
		return eB;
	}

	public void seteB(Integer eB) {
		this.eB = eB;
	}

	public String getFinishStatus() {
		return finishStatus;
	}

	public void setFinishStatus(String finishStatus) {
		this.finishStatus = finishStatus;
	}

	private String adminsNames;
	private String adminNames;
	
	
	public String getAdminNames() {
		return adminNames;
	}

	public void setAdminNames(String adminNames) {
		this.adminNames = adminNames;
	}

	public String getAdminsNames() {
		return adminsNames;
	}

	public void setAdminsNames(String adminsNames) {
		this.adminsNames = adminsNames;
	}

	private String activityCount;
	
	public String getActivityCount() {
		return activityCount;
	}

	public void setActivityCount(String activityCount) {
		this.activityCount = activityCount;
	}

	@FormParam("actPicture")
	private String actPicture;
	@FormParam("actPictureEn")
	private String actPictureEn;
	@FormParam("cityEn")
	private String cityEn;
	
	@FormParam("parentClassifyId")
	private String parentClassifyId;
	
	@FormParam("parentProjectClassifyName")
    private String parentProjectClassifyName;


	public String getParentClassifyId() {
		return parentClassifyId;
	}

	public void setParentClassifyId(String parentClassifyId) {
		this.parentClassifyId = parentClassifyId;
	}

	public String getParentProjectClassifyName() {
		return parentProjectClassifyName;
	}

	public void setParentProjectClassifyName(String parentProjectClassifyName) {
		this.parentProjectClassifyName = parentProjectClassifyName;
	}

	public String getActPictureEn() {
		return actPictureEn;
	}

	public void setActPictureEn(String actPictureEn) {
		this.actPictureEn = actPictureEn;
	}

	public String getCityEn() {
		return cityEn;
	}

	public void setCityEn(String cityEn) {
		this.cityEn = cityEn;
	}

	public String getActPicture() {
		return actPicture;
	}

	public void setActPicture(String actPicture) {
		this.actPicture = actPicture;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated
     */
	@FormParam("activityId[]")
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("activityNumber[]")
    private String activityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated
     */
	@FormParam("activityName[]")
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.INTRODUCTION
     *
     * @mbggenerated
     */
	@FormParam("introduction[]")
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.PROTOCOL
     *
     * @mbggenerated
     */
	@FormParam("protocol[]")
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.PROTOCOL_START_TIME
     *
     * @mbggenerated
     */
    private Date protocolStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.PROTOCOL_END_TIME
     *
     * @mbggenerated
     */
    private Date protocolEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.TRAIN_FEE
     *
     * @mbggenerated
     */
	@FormParam("trainFee[]")
    private Double trainFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.NEED_APPLY
     *
     * @mbggenerated
     */
	@FormParam("needApply[]")
    private String needApply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.NUMBER_OF_PARTICIPANTS
     *
     * @mbggenerated
     */
	@FormParam("numberOfParticipants[]")
    private Integer numberOfParticipants;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.STAFF_LEVELS
     *
     * @mbggenerated
     */
	@FormParam("staffLevels[]")
    private String staffLevels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.CITY
     *
     * @mbggenerated
     */
	@FormParam("city[]")
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ADMINS
     *
     * @mbggenerated
     */
	@FormParam("admins[]")
    private String admins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.APPLICATION_START_TIME
     *
     * @mbggenerated
     */
	@FormParam("applicationStartTime[]")
    private Date applicationStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.APPLICATION_DEADLINE
     *
     * @mbggenerated
     */
	@FormParam("applicationDeadline[]")
    private Date applicationDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_START_TIME
     *
     * @mbggenerated
     */
    private Date activityStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_END_TIME
     *
     * @mbggenerated
     */
    private Date activityEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.DEPTS
     *
     * @mbggenerated
     */
	@FormParam("depts[]")
    private String depts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator[]")
    private String creator;

	@FormParam("creatorId")
    private String creatorId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("createTime[]")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("operator[]")
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;
    
	@FormParam("tomEmp")
    private List<TomEmp> tomEmp;
	
	@Autowired
	private NumberRecordService numberRecordService;
	
	/**
	 * 插入前调用
	 */
	public void preInsertData(){
		//activity.setAdmins("admins");
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.creator = user;
//		this.updateTime = new Date();
//		this.createTime = new Date();
	}
	
	/**
	 * 插入前调用
	 */
	public void preInsertsData(){
	
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.creator = user;
//		this.updateTime = new Date();
//		this.createTime = new Date();
		
		//签订协议
		if(this.protocol.equals("Y")){
			this.protocolStartTime = protocolStartTime;
			this.protocolEndTime = protocolEndTime;
			this.protocol = Global.YES;
		}else{
			this.protocol = Global.NO;
		}
		
		//必修选修  
		if(this.needApply.equals("Y")){
			this.numberOfParticipants = numberOfParticipants;//报名人数
			//this.applicationStartTime = new Date();
			//this.applicationDeadline=new Date();
			this.applicationStartTime = applicationStartTime;
			this.applicationDeadline = applicationDeadline;
			this.needApply = Global.YES;
		}else{
			this.needApply = Global.NO;
		}
	}
	
	
	/**
	 * 插入后调用
	 */
	public void preUpdateData(){
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.updateTime = new Date();
	}

	
	
    public List<TomEmp> getTomEmp() {
		return tomEmp;
	}

	public void setTomEmp(List<TomEmp> tomEmp) {
		this.tomEmp = tomEmp;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ACTIVITY_ID
     *
     * @return the value of TOM_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ACTIVITY_ID
     *
     * @param activityId the value for TOM_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ACTIVITY_NUMBER
     *
     * @return the value of TOM_ACTIVITY.ACTIVITY_NUMBER
     *
     * @mbggenerated
     */
    public String getActivityNumber() {
        return activityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ACTIVITY_NUMBER
     *
     * @param activityNumber the value for TOM_ACTIVITY.ACTIVITY_NUMBER
     *
     * @mbggenerated
     */
    public void setActivityNumber(String activityNumber) {
        this.activityNumber = activityNumber == null ? null : activityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @return the value of TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @param activityName the value for TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.INTRODUCTION
     *
     * @return the value of TOM_ACTIVITY.INTRODUCTION
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.INTRODUCTION
     *
     * @param introduction the value for TOM_ACTIVITY.INTRODUCTION
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.PROTOCOL
     *
     * @return the value of TOM_ACTIVITY.PROTOCOL
     *
     * @mbggenerated
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.PROTOCOL
     *
     * @param protocol the value for TOM_ACTIVITY.PROTOCOL
     *
     * @mbggenerated
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.PROTOCOL_START_TIME
     *
     * @return the value of TOM_ACTIVITY.PROTOCOL_START_TIME
     *
     * @mbggenerated
     */
    public Date getProtocolStartTime() {
        return protocolStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.PROTOCOL_START_TIME
     *
     * @param protocolStartTime the value for TOM_ACTIVITY.PROTOCOL_START_TIME
     *
     * @mbggenerated
     */
    public void setProtocolStartTime(Date protocolStartTime) {
        this.protocolStartTime = protocolStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.PROTOCOL_END_TIME
     *
     * @return the value of TOM_ACTIVITY.PROTOCOL_END_TIME
     *
     * @mbggenerated
     */
    public Date getProtocolEndTime() {
        return protocolEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.PROTOCOL_END_TIME
     *
     * @param protocolEndTime the value for TOM_ACTIVITY.PROTOCOL_END_TIME
     *
     * @mbggenerated
     */
    public void setProtocolEndTime(Date protocolEndTime) {
        this.protocolEndTime = protocolEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.TRAIN_FEE
     *
     * @return the value of TOM_ACTIVITY.TRAIN_FEE
     *
     * @mbggenerated
     */
    public Double getTrainFee() {
        return trainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.TRAIN_FEE
     *
     * @param trainFee the value for TOM_ACTIVITY.TRAIN_FEE
     *
     * @mbggenerated
     */
    public void setTrainFee(Double trainFee) {
        this.trainFee = trainFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.NEED_APPLY
     *
     * @return the value of TOM_ACTIVITY.NEED_APPLY
     *
     * @mbggenerated
     */
    public String getNeedApply() {
        return needApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.NEED_APPLY
     *
     * @param needApply the value for TOM_ACTIVITY.NEED_APPLY
     *
     * @mbggenerated
     */
    public void setNeedApply(String needApply) {
        this.needApply = needApply == null ? null : needApply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.NUMBER_OF_PARTICIPANTS
     *
     * @return the value of TOM_ACTIVITY.NUMBER_OF_PARTICIPANTS
     *
     * @mbggenerated
     */
    public Integer getNumberOfParticipants() {
        return numberOfParticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.NUMBER_OF_PARTICIPANTS
     *
     * @param numberOfParticipants the value for TOM_ACTIVITY.NUMBER_OF_PARTICIPANTS
     *
     * @mbggenerated
     */
    public void setNumberOfParticipants(Integer numberOfParticipants) {
        this.numberOfParticipants = numberOfParticipants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.STAFF_LEVELS
     *
     * @return the value of TOM_ACTIVITY.STAFF_LEVELS
     *
     * @mbggenerated
     */
    public String getStaffLevels() {
        return staffLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.STAFF_LEVELS
     *
     * @param staffLevels the value for TOM_ACTIVITY.STAFF_LEVELS
     *
     * @mbggenerated
     */
    public void setStaffLevels(String staffLevels) {
        this.staffLevels = staffLevels == null ? null : staffLevels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.CITY
     *
     * @return the value of TOM_ACTIVITY.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.CITY
     *
     * @param city the value for TOM_ACTIVITY.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ADMINS
     *
     * @return the value of TOM_ACTIVITY.ADMINS
     *
     * @mbggenerated
     */
    public String getAdmins() {
        return admins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ADMINS
     *
     * @param admins the value for TOM_ACTIVITY.ADMINS
     *
     * @mbggenerated
     */
    public void setAdmins(String admins) {
        this.admins = admins == null ? null : admins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.APPLICATION_START_TIME
     *
     * @return the value of TOM_ACTIVITY.APPLICATION_START_TIME
     *
     * @mbggenerated
     */
    public Date getApplicationStartTime() {
        return applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.APPLICATION_START_TIME
     *
     * @param applicationStartTime the value for TOM_ACTIVITY.APPLICATION_START_TIME
     *
     * @mbggenerated
     */
    public void setApplicationStartTime(Date applicationStartTime) {
        this.applicationStartTime = applicationStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.APPLICATION_DEADLINE
     *
     * @return the value of TOM_ACTIVITY.APPLICATION_DEADLINE
     *
     * @mbggenerated
     */
    public Date getApplicationDeadline() {
        return applicationDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.APPLICATION_DEADLINE
     *
     * @param applicationDeadline the value for TOM_ACTIVITY.APPLICATION_DEADLINE
     *
     * @mbggenerated
     */
    public void setApplicationDeadline(Date applicationDeadline) {
        this.applicationDeadline = applicationDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ACTIVITY_START_TIME
     *
     * @return the value of TOM_ACTIVITY.ACTIVITY_START_TIME
     *
     * @mbggenerated
     */
    public Date getActivityStartTime() {
        return activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ACTIVITY_START_TIME
     *
     * @param activityStartTime the value for TOM_ACTIVITY.ACTIVITY_START_TIME
     *
     * @mbggenerated
     */
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.ACTIVITY_END_TIME
     *
     * @return the value of TOM_ACTIVITY.ACTIVITY_END_TIME
     *
     * @mbggenerated
     */
    public Date getActivityEndTime() {
        return activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.ACTIVITY_END_TIME
     *
     * @param activityEndTime the value for TOM_ACTIVITY.ACTIVITY_END_TIME
     *
     * @mbggenerated
     */
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.DEPTS
     *
     * @return the value of TOM_ACTIVITY.DEPTS
     *
     * @mbggenerated
     */
    public String getDepts() {
        return depts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.DEPTS
     *
     * @param depts the value for TOM_ACTIVITY.DEPTS
     *
     * @mbggenerated
     */
    public void setDepts(String depts) {
        this.depts = depts == null ? null : depts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.CREATOR
     *
     * @return the value of TOM_ACTIVITY.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.CREATOR
     *
     * @param creator the value for TOM_ACTIVITY.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.CREATE_TIME
     *
     * @return the value of TOM_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.CREATE_TIME
     *
     * @param createTime the value for TOM_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.OPERATOR
     *
     * @return the value of TOM_ACTIVITY.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.OPERATOR
     *
     * @param operator the value for TOM_ACTIVITY.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY.UPDATE_TIME
     *
     * @return the value of TOM_ACTIVITY.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY.UPDATE_TIME
     *
     * @param updateTime the value for TOM_ACTIVITY.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public String getImgpath() {
		return imgpath;
	}

	public void setImgpath(String imgpath) {
		this.imgpath = imgpath;
	}
	
	
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated
     */
	@FormParam("activityNameEn[]")
    private String activityNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.INTRODUCTION
     *
     * @mbggenerated
     */
	@FormParam("introductionEn[]")
    private String introductionEn;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY.CITY
     *
     * @mbggenerated
     */
	

	public String getActivityNameEn() {
		return activityNameEn;
	}

	public void setActivityNameEn(String activityNameEn) {
		this.activityNameEn = activityNameEn;
	}

	public String getIntroductionEn() {
		return introductionEn;
	}

	public void setIntroductionEn(String introductionEn) {
		this.introductionEn = introductionEn;
	}

	
	
    
}