package com.chinamobo.ue.activity.entity;

import java.util.Date;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.common.DataEntity;

public class TomActivityProperty extends DataEntity<TomActivityProperty> {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.ACTIVITY_ID
	 *
	 * @mbggenerated
	 */
	@FormParam("activityId")
	private Integer activityId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.PACKAGE_ID
	 *
	 * @mbggenerated
	 */
	@FormParam("packageId")
	private Integer packageId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.SORT
	 *
	 * @mbggenerated
	 */
	@FormParam("sort")
	private Integer sort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.START_TIME
	 *
	 * @mbggenerated
	 */
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.END_TIME
	 *
	 * @mbggenerated
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.LECTURERS
	 *
	 * @mbggenerated
	 */
	@FormParam("lecturers")
	private String lecturers;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.COURSE_ID
	 *
	 * @mbggenerated
	 */
	@FormParam("courseId")
	private Integer courseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.COURSE_ADDRESS
	 *
	 * @mbggenerated
	 */
	@FormParam("courseAddress")
	private String courseAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.COURSE_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("courseTime")
	private Double courseTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.UNIT_PRICE
	 *
	 * @mbggenerated
	 */
	@FormParam("unitPrice")
	private Double unitPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.TOTAL_PRICE
	 *
	 * @mbggenerated
	 */
	@FormParam("totalPrice")
	private Double totalPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.EXAM_NAME
	 *
	 * @mbggenerated
	 */
	@FormParam("examName")
	private String examName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.EXAM_ID
	 *
	 * @mbggenerated
	 */
	@FormParam("examId")
	private Integer examId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.EXAM_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("examTime")
	private Double examTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.RETAKING_EXAM_TIMES
	 *
	 * @mbggenerated
	 */
	@FormParam("retakingExamTimes")
	private Integer retakingExamTimes;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.OFFLINE_EXAM
	 *
	 * @mbggenerated
	 */
	@FormParam("offlineExam")
	private String offlineExam;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.PRE_TASK
	 *
	 * @mbggenerated
	 */
	@FormParam("preTask")
	private String preTask;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.CREATOR
	 *
	 * @mbggenerated
	 */
	@FormParam("creator")
	private String creator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("createTime")
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.OPERATOR
	 *
	 * @mbggenerated
	 */
	@FormParam("operator")
	private String operator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_PROPERTY.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("updateTime")
	private Date updateTime;

	@FormParam("signInTwoDimensionCode")
	private String signInTwoDimensionCode;

	@FormParam("gradeTwoDimensionCode")
	private String gradeTwoDimensionCode;

	public String getSignInTwoDimensionCode() {
		return signInTwoDimensionCode;
	}

	public void setSignInTwoDimensionCode(String signInTwoDimensionCode) {
		this.signInTwoDimensionCode = signInTwoDimensionCode;
	}

	public String getGradeTwoDimensionCode() {
		return gradeTwoDimensionCode;
	}

	public void setGradeTwoDimensionCode(String gradeTwoDimensionCode) {
		this.gradeTwoDimensionCode = gradeTwoDimensionCode;
	}

	/**
	 * 插入前调用
	 */
	public void preInsertData() {

		// String user = ShiroUtils.getCurrentUser().getName();
		// String user = "4";
		// this.operator = user;
		// this.creator = user;
		// this.updateTime = new Date();
		// this.createTime = new Date();
	}

	/**
	 * 插入后调用
	 */
	public void preUpdateData() {
		// String user = ShiroUtils.getCurrentUser().getName();
		// String user = "4";
		// this.operator = user;
		// this.updateTime = new Date();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.ACTIVITY_ID
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.ACTIVITY_ID
	 *
	 * @mbggenerated
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.ACTIVITY_ID
	 *
	 * @param activityId
	 *            the value for TOM_ACTIVITY_PROPERTY.ACTIVITY_ID
	 *
	 * @mbggenerated
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.PACKAGE_ID
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.PACKAGE_ID
	 *
	 * @mbggenerated
	 */
	public Integer getPackageId() {
		return packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.PACKAGE_ID
	 *
	 * @param packageId
	 *            the value for TOM_ACTIVITY_PROPERTY.PACKAGE_ID
	 *
	 * @mbggenerated
	 */
	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.SORT
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.SORT
	 *
	 * @mbggenerated
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.SORT
	 *
	 * @param sort
	 *            the value for TOM_ACTIVITY_PROPERTY.SORT
	 *
	 * @mbggenerated
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.START_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.START_TIME
	 *
	 * @mbggenerated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.START_TIME
	 *
	 * @param startTime
	 *            the value for TOM_ACTIVITY_PROPERTY.START_TIME
	 *
	 * @mbggenerated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.END_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.END_TIME
	 *
	 * @mbggenerated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.END_TIME
	 *
	 * @param endTime
	 *            the value for TOM_ACTIVITY_PROPERTY.END_TIME
	 *
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.LECTURERS
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.LECTURERS
	 *
	 * @mbggenerated
	 */
	public String getLecturers() {
		return lecturers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.LECTURERS
	 *
	 * @param lecturers
	 *            the value for TOM_ACTIVITY_PROPERTY.LECTURERS
	 *
	 * @mbggenerated
	 */
	public void setLecturers(String lecturers) {
		this.lecturers = lecturers == null ? null : lecturers.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_ID
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.COURSE_ID
	 *
	 * @mbggenerated
	 */
	public Integer getCourseId() {
		return courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_ID
	 *
	 * @param courseId
	 *            the value for TOM_ACTIVITY_PROPERTY.COURSE_ID
	 *
	 * @mbggenerated
	 */
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_ADDRESS
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.COURSE_ADDRESS
	 *
	 * @mbggenerated
	 */
	public String getCourseAddress() {
		return courseAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_ADDRESS
	 *
	 * @param courseAddress
	 *            the value for TOM_ACTIVITY_PROPERTY.COURSE_ADDRESS
	 *
	 * @mbggenerated
	 */
	public void setCourseAddress(String courseAddress) {
		this.courseAddress = courseAddress == null ? null : courseAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.COURSE_TIME
	 *
	 * @mbggenerated
	 */
	public Double getCourseTime() {
		return courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.COURSE_TIME
	 *
	 * @param courseTime
	 *            the value for TOM_ACTIVITY_PROPERTY.COURSE_TIME
	 *
	 * @mbggenerated
	 */
	public void setCourseTime(Double courseTime) {
		this.courseTime = courseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.UNIT_PRICE
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.UNIT_PRICE
	 *
	 * @mbggenerated
	 */
	public Double getUnitPrice() {
		return unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.UNIT_PRICE
	 *
	 * @param unitPrice
	 *            the value for TOM_ACTIVITY_PROPERTY.UNIT_PRICE
	 *
	 * @mbggenerated
	 */
	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.TOTAL_PRICE
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.TOTAL_PRICE
	 *
	 * @mbggenerated
	 */
	public Double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.TOTAL_PRICE
	 *
	 * @param totalPrice
	 *            the value for TOM_ACTIVITY_PROPERTY.TOTAL_PRICE
	 *
	 * @mbggenerated
	 */
	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_NAME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.EXAM_NAME
	 *
	 * @mbggenerated
	 */
	public String getExamName() {
		return examName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_NAME
	 *
	 * @param examName
	 *            the value for TOM_ACTIVITY_PROPERTY.EXAM_NAME
	 *
	 * @mbggenerated
	 */
	public void setExamName(String examName) {
		this.examName = examName == null ? null : examName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_ID
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.EXAM_ID
	 *
	 * @mbggenerated
	 */
	public Integer getExamId() {
		return examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_ID
	 *
	 * @param examId
	 *            the value for TOM_ACTIVITY_PROPERTY.EXAM_ID
	 *
	 * @mbggenerated
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.EXAM_TIME
	 *
	 * @mbggenerated
	 */
	public Double getExamTime() {
		return examTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.EXAM_TIME
	 *
	 * @param examTime
	 *            the value for TOM_ACTIVITY_PROPERTY.EXAM_TIME
	 *
	 * @mbggenerated
	 */
	public void setExamTime(Double examTime) {
		this.examTime = examTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.RETAKING_EXAM_TIMES
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.RETAKING_EXAM_TIMES
	 *
	 * @mbggenerated
	 */
	public Integer getRetakingExamTimes() {
		return retakingExamTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.RETAKING_EXAM_TIMES
	 *
	 * @param retakingExamTimes
	 *            the value for TOM_ACTIVITY_PROPERTY.RETAKING_EXAM_TIMES
	 *
	 * @mbggenerated
	 */
	public void setRetakingExamTimes(Integer retakingExamTimes) {
		this.retakingExamTimes = retakingExamTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.OFFLINE_EXAM
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.OFFLINE_EXAM
	 *
	 * @mbggenerated
	 */
	public String getOfflineExam() {
		return offlineExam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.OFFLINE_EXAM
	 *
	 * @param offlineExam
	 *            the value for TOM_ACTIVITY_PROPERTY.OFFLINE_EXAM
	 *
	 * @mbggenerated
	 */
	public void setOfflineExam(String offlineExam) {
		this.offlineExam = offlineExam == null ? null : offlineExam.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.PRE_TASK
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.PRE_TASK
	 *
	 * @mbggenerated
	 */
	public String getPreTask() {
		return preTask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.PRE_TASK
	 *
	 * @param preTask
	 *            the value for TOM_ACTIVITY_PROPERTY.PRE_TASK
	 *
	 * @mbggenerated
	 */
	public void setPreTask(String preTask) {
		this.preTask = preTask == null ? null : preTask.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.CREATOR
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.CREATOR
	 *
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.CREATOR
	 *
	 * @param creator
	 *            the value for TOM_ACTIVITY_PROPERTY.CREATOR
	 *
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.CREATE_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.CREATE_TIME
	 *
	 * @param createTime
	 *            the value for TOM_ACTIVITY_PROPERTY.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.OPERATOR
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.OPERATOR
	 *
	 * @mbggenerated
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.OPERATOR
	 *
	 * @param operator
	 *            the value for TOM_ACTIVITY_PROPERTY.OPERATOR
	 *
	 * @mbggenerated
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_PROPERTY.UPDATE_TIME
	 *
	 * @return the value of TOM_ACTIVITY_PROPERTY.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_PROPERTY.UPDATE_TIME
	 *
	 * @param updateTime
	 *            the value for TOM_ACTIVITY_PROPERTY.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private Date activityStartTime;
	private Date activityEndTime;

	public Date getActivityStartTime() {
		return activityStartTime;
	}

	public void setActivityStartTime(Date activityStartTime) {
		this.activityStartTime = activityStartTime;
	}

	public Date getActivityEndTime() {
		return activityEndTime;
	}

	public void setActivityEndTime(Date activityEndTime) {
		this.activityEndTime = activityEndTime;
	}

	private String courseOnline;// 线上线下状态

	public String getCourseOnline() {
		return courseOnline;
	}

	public void setCourseOnline(String courseOnline) {
		this.courseOnline = courseOnline;
	}

	private String status;
	private Integer id;
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}