package com.chinamobo.ue.activity.entity;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.common.DataEntity;

public class TomActivityEmpsRelationKey extends DataEntity<TomActivityEmpsRelationKey>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_EMPS_RELATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
	@FormParam("activityId")
	private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_EMPS_RELATION.CODE
     *
     * @mbggenerated
     */
	@FormParam("code")
	private String code;
	
	
	@FormParam("name")
	private String name;
	
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_EMPS_RELATION.ACTIVITY_ID
     *
     * @return the value of TOM_ACTIVITY_EMPS_RELATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_EMPS_RELATION.ACTIVITY_ID
     *
     * @param activityId the value for TOM_ACTIVITY_EMPS_RELATION.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_EMPS_RELATION.CODE
     *
     * @return the value of TOM_ACTIVITY_EMPS_RELATION.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_EMPS_RELATION.CODE
     *
     * @param code the value for TOM_ACTIVITY_EMPS_RELATION.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}