package com.chinamobo.ue.activity.entity;

import java.util.Date;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.common.DataEntity;
import com.chinamobo.ue.utils.Global;

public class TomActivityDept extends DataEntity<TomActivityDept>{
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.ACTIVITY_ID
     *
     * @mbggenerated
     */
	@FormParam("activityId")
	private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.HEADER_CODE
     *
     * @mbggenerated
     */
	@FormParam("headerCode")
	private String headerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.CODE
     *
     * @mbggenerated
     */
	@FormParam("code")
	private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
	private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.CREATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("createTime")
	private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("operator")
	private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.UPDATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("updateTime")
	private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ACTIVITY_DEPT.STATUS
     *
     * @mbggenerated
     */
	@FormParam("status")
	private String status;
	@FormParam("pushStatus")
	private String pushStatus;
    

	/**
	 * 插入前调用
	 */
	public void preInsertData(){
	
//		String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.creator = user;
//		this.updateTime = new Date();
//		this.createTime = new Date();
		this.status = Global.ZC;//Y 正常  N 取消关联
	}
	
	/**
	 * 插入后调用
	 */
	public void preUpdateData(){
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.updateTime = new Date();
	}
	
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.ACTIVITY_ID
     *
     * @return the value of TOM_ACTIVITY_DEPT.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.ACTIVITY_ID
     *
     * @param activityId the value for TOM_ACTIVITY_DEPT.ACTIVITY_ID
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.HEADER_CODE
     *
     * @return the value of TOM_ACTIVITY_DEPT.HEADER_CODE
     *
     * @mbggenerated
     */
    public String getHeaderCode() {
        return headerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.HEADER_CODE
     *
     * @param headerCode the value for TOM_ACTIVITY_DEPT.HEADER_CODE
     *
     * @mbggenerated
     */
    public void setHeaderCode(String headerCode) {
        this.headerCode = headerCode == null ? null : headerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.CODE
     *
     * @return the value of TOM_ACTIVITY_DEPT.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.CODE
     *
     * @param code the value for TOM_ACTIVITY_DEPT.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.CREATOR
     *
     * @return the value of TOM_ACTIVITY_DEPT.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.CREATOR
     *
     * @param creator the value for TOM_ACTIVITY_DEPT.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.CREATE_TIME
     *
     * @return the value of TOM_ACTIVITY_DEPT.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.CREATE_TIME
     *
     * @param createTime the value for TOM_ACTIVITY_DEPT.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.OPERATOR
     *
     * @return the value of TOM_ACTIVITY_DEPT.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.OPERATOR
     *
     * @param operator the value for TOM_ACTIVITY_DEPT.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.UPDATE_TIME
     *
     * @return the value of TOM_ACTIVITY_DEPT.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.UPDATE_TIME
     *
     * @param updateTime the value for TOM_ACTIVITY_DEPT.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ACTIVITY_DEPT.STATUS
     *
     * @return the value of TOM_ACTIVITY_DEPT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ACTIVITY_DEPT.STATUS
     *
     * @param status the value for TOM_ACTIVITY_DEPT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	public String getPushStatus() {
		return pushStatus;
	}

	public void setPushStatus(String pushStatus) {
		this.pushStatus = pushStatus;
	}
    
}