package com.chinamobo.ue.activity.entity;

import java.util.Date;

import javax.ws.rs.FormParam;

public class TomProjectClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_id
     *
     * @mbggenerated
     */
	@FormParam("projectId")
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_name
     *
     * @mbggenerated
     */
    @FormParam("projectName")
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_name_en
     *
     * @mbggenerated
     */
    @FormParam("projectNameEn")
    private String projectNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_number
     *
     * @mbggenerated
     */
    private String projectNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.parent_project_id
     *
     * @mbggenerated
     */
    @FormParam("parentClassifyId")
    private Integer parentProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_introduction
     *
     * @mbggenerated
     */
    @FormParam("projectIntroduction")
    private String projectIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.project_introduction_en
     *
     * @mbggenerated
     */
    @FormParam("projectIntroductionEn")
    private String projectIntroductionEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.admins
     *
     * @mbggenerated
     */
    @FormParam("admins")
    private String admins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.creator_id
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_project_classify.operator_id
     *
     * @mbggenerated
     */
    private String operatorId;

    @FormParam("parentProjectClassifyName")
    private String parentClassifyName;
    
    public String getParentClassifyName() {
		return parentClassifyName;
	}

	public void setParentClassifyName(String parentClassifyName) {
		this.parentClassifyName = parentClassifyName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_id
     *
     * @return the value of tom_project_classify.project_id
     *
     * @mbggenerated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_id
     *
     * @param projectId the value for tom_project_classify.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_name
     *
     * @return the value of tom_project_classify.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_name
     *
     * @param projectName the value for tom_project_classify.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_name_en
     *
     * @return the value of tom_project_classify.project_name_en
     *
     * @mbggenerated
     */
    public String getProjectNameEn() {
        return projectNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_name_en
     *
     * @param projectNameEn the value for tom_project_classify.project_name_en
     *
     * @mbggenerated
     */
    public void setProjectNameEn(String projectNameEn) {
        this.projectNameEn = projectNameEn == null ? null : projectNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_number
     *
     * @return the value of tom_project_classify.project_number
     *
     * @mbggenerated
     */
    public String getProjectNumber() {
        return projectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_number
     *
     * @param projectNumber the value for tom_project_classify.project_number
     *
     * @mbggenerated
     */
    public void setProjectNumber(String projectNumber) {
        this.projectNumber = projectNumber == null ? null : projectNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.parent_project_id
     *
     * @return the value of tom_project_classify.parent_project_id
     *
     * @mbggenerated
     */
    public Integer getParentProjectId() {
        return parentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.parent_project_id
     *
     * @param parentProjectId the value for tom_project_classify.parent_project_id
     *
     * @mbggenerated
     */
    public void setParentProjectId(Integer parentProjectId) {
        this.parentProjectId = parentProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_introduction
     *
     * @return the value of tom_project_classify.project_introduction
     *
     * @mbggenerated
     */
    public String getProjectIntroduction() {
        return projectIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_introduction
     *
     * @param projectIntroduction the value for tom_project_classify.project_introduction
     *
     * @mbggenerated
     */
    public void setProjectIntroduction(String projectIntroduction) {
        this.projectIntroduction = projectIntroduction == null ? null : projectIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.project_introduction_en
     *
     * @return the value of tom_project_classify.project_introduction_en
     *
     * @mbggenerated
     */
    public String getProjectIntroductionEn() {
        return projectIntroductionEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.project_introduction_en
     *
     * @param projectIntroductionEn the value for tom_project_classify.project_introduction_en
     *
     * @mbggenerated
     */
    public void setProjectIntroductionEn(String projectIntroductionEn) {
        this.projectIntroductionEn = projectIntroductionEn == null ? null : projectIntroductionEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.admins
     *
     * @return the value of tom_project_classify.admins
     *
     * @mbggenerated
     */
    public String getAdmins() {
        return admins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.admins
     *
     * @param admins the value for tom_project_classify.admins
     *
     * @mbggenerated
     */
    public void setAdmins(String admins) {
        this.admins = admins == null ? null : admins.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.creator
     *
     * @return the value of tom_project_classify.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.creator
     *
     * @param creator the value for tom_project_classify.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.create_time
     *
     * @return the value of tom_project_classify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.create_time
     *
     * @param createTime the value for tom_project_classify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.operator
     *
     * @return the value of tom_project_classify.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.operator
     *
     * @param operator the value for tom_project_classify.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.update_time
     *
     * @return the value of tom_project_classify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.update_time
     *
     * @param updateTime the value for tom_project_classify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.creator_id
     *
     * @return the value of tom_project_classify.creator_id
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.creator_id
     *
     * @param creatorId the value for tom_project_classify.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_project_classify.operator_id
     *
     * @return the value of tom_project_classify.operator_id
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_project_classify.operator_id
     *
     * @param operatorId the value for tom_project_classify.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }
    
}