package com.chinamobo.ue.activity.entity;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.common.DataEntity;

public class TomTaskCoursesRelationKey extends DataEntity<TomTaskCoursesRelationKey>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TASK_COURSES_RELATION.PACKAGE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
	@FormParam("packageId")
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TASK_COURSES_RELATION.COURSE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
	@FormParam("courseId")
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TASK_COURSES_RELATION.PACKAGE_ID
     *
     * @return the value of TOM_TASK_COURSES_RELATION.PACKAGE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TASK_COURSES_RELATION.PACKAGE_ID
     *
     * @param packageId the value for TOM_TASK_COURSES_RELATION.PACKAGE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TASK_COURSES_RELATION.COURSE_ID
     *
     * @return the value of TOM_TASK_COURSES_RELATION.COURSE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TASK_COURSES_RELATION.COURSE_ID
     *
     * @param courseId the value for TOM_TASK_COURSES_RELATION.COURSE_ID
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}