package com.chinamobo.ue.activity.entity;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.common.DataEntity;

public class TomTaskExamPaperRelationKey extends DataEntity<TomTaskExamPaperRelationKey>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TASK_EXAM_RELATION.PACKAGE_ID
     *
     * @mbggenerated
     */
	@FormParam("packageId")
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_TASK_EXAM_RELATION.EXAM_ID
     *
     * @mbggenerated
     */
	@FormParam("examPaperId")
    private Integer examPaperId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TASK_EXAM_RELATION.PACKAGE_ID
     *
     * @return the value of TOM_TASK_EXAM_RELATION.PACKAGE_ID
     *
     * @mbggenerated
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TASK_EXAM_RELATION.PACKAGE_ID
     *
     * @param packageId the value for TOM_TASK_EXAM_RELATION.PACKAGE_ID
     *
     * @mbggenerated
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_TASK_EXAM_RELATION.EXAM_ID
     *
     * @return the value of TOM_TASK_EXAM_RELATION.EXAM_ID
     *
     * @mbggenerated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_TASK_EXAM_RELATION.EXAM_ID
     *
     * @param examId the value for TOM_TASK_EXAM_RELATION.EXAM_ID
     *
     * @mbggenerated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }
}