package com.chinamobo.ue.system.entity;

import java.util.Date;

public class TomAuthoritiesTypeRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_AUTHORITIES_TYPE_ROLE.authority_type_id
     *
     * @mbggenerated
     */
    private Integer authorityTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_AUTHORITIES_TYPE_ROLE.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_AUTHORITIES_TYPE_ROLE.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_AUTHORITIES_TYPE_ROLE.authority_type_id
     *
     * @return the value of TOM_AUTHORITIES_TYPE_ROLE.authority_type_id
     *
     * @mbggenerated
     */
    public Integer getAuthorityTypeId() {
        return authorityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_AUTHORITIES_TYPE_ROLE.authority_type_id
     *
     * @param authorityTypeId the value for TOM_AUTHORITIES_TYPE_ROLE.authority_type_id
     *
     * @mbggenerated
     */
    public void setAuthorityTypeId(Integer authorityTypeId) {
        this.authorityTypeId = authorityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_AUTHORITIES_TYPE_ROLE.role_id
     *
     * @return the value of TOM_AUTHORITIES_TYPE_ROLE.role_id
     *
     * @mbggenerated
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_AUTHORITIES_TYPE_ROLE.create_time
     *
     * @return the value of TOM_AUTHORITIES_TYPE_ROLE.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_AUTHORITIES_TYPE_ROLE.create_time
     *
     * @param createTime the value for TOM_AUTHORITIES_TYPE_ROLE.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}