package com.chinamobo.ue.system.entity;

import java.util.Date;

public class TomAppErrorLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.ERROR_ID
     *
     * @mbggenerated
     */
    private Integer errorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.PLATFORM
     *
     * @mbggenerated
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.VERSION_NUMBER
     *
     * @mbggenerated
     */
    private String versionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    private String equipmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.SYSTEM_VERSION
     *
     * @mbggenerated
     */
    private String systemVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.ERROR_DETAILS
     *
     * @mbggenerated
     */
    private String errorDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_APP_ERROR_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.ERROR_ID
     *
     * @return the value of TOM_APP_ERROR_LOG.ERROR_ID
     *
     * @mbggenerated
     */
    public Integer getErrorId() {
        return errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.ERROR_ID
     *
     * @param errorId the value for TOM_APP_ERROR_LOG.ERROR_ID
     *
     * @mbggenerated
     */
    public void setErrorId(Integer errorId) {
        this.errorId = errorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.PLATFORM
     *
     * @return the value of TOM_APP_ERROR_LOG.PLATFORM
     *
     * @mbggenerated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.PLATFORM
     *
     * @param platform the value for TOM_APP_ERROR_LOG.PLATFORM
     *
     * @mbggenerated
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.VERSION_NUMBER
     *
     * @return the value of TOM_APP_ERROR_LOG.VERSION_NUMBER
     *
     * @mbggenerated
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.VERSION_NUMBER
     *
     * @param versionNumber the value for TOM_APP_ERROR_LOG.VERSION_NUMBER
     *
     * @mbggenerated
     */
    public void setVersionNumber(String versionNumber) {
        this.versionNumber = versionNumber == null ? null : versionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.EQUIPMENT_NAME
     *
     * @return the value of TOM_APP_ERROR_LOG.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.EQUIPMENT_NAME
     *
     * @param equipmentName the value for TOM_APP_ERROR_LOG.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.SYSTEM_VERSION
     *
     * @return the value of TOM_APP_ERROR_LOG.SYSTEM_VERSION
     *
     * @mbggenerated
     */
    public String getSystemVersion() {
        return systemVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.SYSTEM_VERSION
     *
     * @param systemVersion the value for TOM_APP_ERROR_LOG.SYSTEM_VERSION
     *
     * @mbggenerated
     */
    public void setSystemVersion(String systemVersion) {
        this.systemVersion = systemVersion == null ? null : systemVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.ERROR_DETAILS
     *
     * @return the value of TOM_APP_ERROR_LOG.ERROR_DETAILS
     *
     * @mbggenerated
     */
    public String getErrorDetails() {
        return errorDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.ERROR_DETAILS
     *
     * @param errorDetails the value for TOM_APP_ERROR_LOG.ERROR_DETAILS
     *
     * @mbggenerated
     */
    public void setErrorDetails(String errorDetails) {
        this.errorDetails = errorDetails == null ? null : errorDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_APP_ERROR_LOG.CREATE_TIME
     *
     * @return the value of TOM_APP_ERROR_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_APP_ERROR_LOG.CREATE_TIME
     *
     * @param createTime the value for TOM_APP_ERROR_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}