package com.chinamobo.ue.system.entity;

import java.util.Date;

public class TomInterfLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_INTERF_LOG.LOG_ID
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_INTERF_LOG.OPERATION_SIGN
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_INTERF_LOG.LOG_INFO
     *
     * @mbggenerated
     */
    private String logInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_INTERF_LOG.INTERFACE_NAME
     *
     * @mbggenerated
     */
    private String interfaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_INTERF_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_INTERF_LOG.LOG_ID
     *
     * @return the value of TOM_INTERF_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_INTERF_LOG.LOG_ID
     *
     * @param logId the value for TOM_INTERF_LOG.LOG_ID
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }


    public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_INTERF_LOG.LOG_INFO
     *
     * @return the value of TOM_INTERF_LOG.LOG_INFO
     *
     * @mbggenerated
     */
    public String getLogInfo() {
        return logInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_INTERF_LOG.LOG_INFO
     *
     * @param logInfo the value for TOM_INTERF_LOG.LOG_INFO
     *
     * @mbggenerated
     */
    public void setLogInfo(String logInfo) {
        this.logInfo = logInfo == null ? null : logInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_INTERF_LOG.INTERFACE_NAME
     *
     * @return the value of TOM_INTERF_LOG.INTERFACE_NAME
     *
     * @mbggenerated
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_INTERF_LOG.INTERFACE_NAME
     *
     * @param interfaceName the value for TOM_INTERF_LOG.INTERFACE_NAME
     *
     * @mbggenerated
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_INTERF_LOG.CREATE_TIME
     *
     * @return the value of TOM_INTERF_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_INTERF_LOG.CREATE_TIME
     *
     * @param createTime the value for TOM_INTERF_LOG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}