package com.chinamobo.ue.system.entity;

import java.util.Date;

public class TomMessageDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.deleted
     *
     * @mbggenerated
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.operater
     *
     * @mbggenerated
     */
    private String operater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tom_message_details.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.id
     *
     * @return the value of tom_message_details.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.id
     *
     * @param id the value for tom_message_details.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.code
     *
     * @return the value of tom_message_details.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.code
     *
     * @param code the value for tom_message_details.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.name
     *
     * @return the value of tom_message_details.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.name
     *
     * @param name the value for tom_message_details.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.message
     *
     * @return the value of tom_message_details.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.message
     *
     * @param message the value for tom_message_details.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.status
     *
     * @return the value of tom_message_details.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.status
     *
     * @param status the value for tom_message_details.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.deleted
     *
     * @return the value of tom_message_details.deleted
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.deleted
     *
     * @param deleted the value for tom_message_details.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.operater
     *
     * @return the value of tom_message_details.operater
     *
     * @mbggenerated
     */
    public String getOperater() {
        return operater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.operater
     *
     * @param operater the value for tom_message_details.operater
     *
     * @mbggenerated
     */
    public void setOperater(String operater) {
        this.operater = operater == null ? null : operater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tom_message_details.update_time
     *
     * @return the value of tom_message_details.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tom_message_details.update_time
     *
     * @param updateTime the value for tom_message_details.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}