package com.chinamobo.ue.system.entity;

import java.util.Date;

public class TomNumberRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NUMBER_RECORD.NUMBER_ID
     *
     * @mbggenerated
     */
    private Integer numberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NUMBER_RECORD.BELONG
     *
     * @mbggenerated
     */
    private String belong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NUMBER_RECORD.TAIL_NUMBER
     *
     * @mbggenerated
     */
    private Integer tailNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_NUMBER_RECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_NUMBER_RECORD.NUMBER_ID
     *
     * @return the value of TOM_NUMBER_RECORD.NUMBER_ID
     *
     * @mbggenerated
     */
    public Integer getNumberId() {
        return numberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_NUMBER_RECORD.NUMBER_ID
     *
     * @param numberId the value for TOM_NUMBER_RECORD.NUMBER_ID
     *
     * @mbggenerated
     */
    public void setNumberId(Integer numberId) {
        this.numberId = numberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_NUMBER_RECORD.BELONG
     *
     * @return the value of TOM_NUMBER_RECORD.BELONG
     *
     * @mbggenerated
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_NUMBER_RECORD.BELONG
     *
     * @param belong the value for TOM_NUMBER_RECORD.BELONG
     *
     * @mbggenerated
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_NUMBER_RECORD.TAIL_NUMBER
     *
     * @return the value of TOM_NUMBER_RECORD.TAIL_NUMBER
     *
     * @mbggenerated
     */
    public Integer getTailNumber() {
        return tailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_NUMBER_RECORD.TAIL_NUMBER
     *
     * @param tailNumber the value for TOM_NUMBER_RECORD.TAIL_NUMBER
     *
     * @mbggenerated
     */
    public void setTailNumber(Integer tailNumber) {
        this.tailNumber = tailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_NUMBER_RECORD.CREATE_TIME
     *
     * @return the value of TOM_NUMBER_RECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_NUMBER_RECORD.CREATE_TIME
     *
     * @param createTime the value for TOM_NUMBER_RECORD.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}