package com.chinamobo.ue.system.entity;

import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.ws.rs.FormParam;

public class TomRollingPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.PICTURE_ID
     *
     * @mbggenerated
     */
	@FormParam("pictureId")
    private Integer pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.RESOURCE_ID
     *
     * @mbggenerated
     */
	@FormParam("resourceId")
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.PICTURE_CATEGORY
     *
     * @mbggenerated
     */
	@FormParam("pictureCategory")
    private String pictureCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @mbggenerated
     */
	@FormParam("pictureUrl")
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.RELEASE_TIME
     *
     * @mbggenerated
     */
	
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.VIEW_COUNT
     *
     * @mbggenerated
     */
	@FormParam("viewCount")
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.IS_RELEASE
     *
     * @mbggenerated
     */
	@FormParam("isRelease")
    private String isRelease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.IS_TOP
     *
     * @mbggenerated
     */
	@FormParam("isTop")
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.ADMINISTRATORS
     *
     * @mbggenerated
     */
	@FormParam("admins")
    private String admins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.CREATER
     *
     * @mbggenerated
     */
	@FormParam("creater")
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.CREATE_TIME
     *
     * @mbggenerated
     */
	
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("operator")
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.UPDATE_TIME
     *
     * @mbggenerated
     */
	
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.DELETED
     *
     * @mbggenerated
     */
	@FormParam("deleted")
    private String deleted;
	
	@FormParam("realeaser")
    private String releaser;

	@FormParam("emps")
	private List<Map<String,String>> emps;
	
	@FormParam("isRollingAllEmp")
	private String isRollingAllEmp;

	public String getReleaser() {
		return releaser;
	}

	public void setReleaser(String releaser) {
		this.releaser = releaser;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.PICTURE_ID
     *
     * @return the value of TOM_ROLLING_PICTURE.PICTURE_ID
     *
     * @mbggenerated
     */
	@FormParam("adminNames")
    private String adminNames;
	@FormParam("creatorId")
    private String creatorId;
	@FormParam("resourceName")
	private String resourceName;
	@FormParam("empIds")
	private String empIds;
	
    public String getAdminNames() {
		return adminNames;
	}

	public void setAdminNames(String adminNames) {
		this.adminNames = adminNames;
	}

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public Integer getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.PICTURE_ID
     *
     * @param pictureId the value for TOM_ROLLING_PICTURE.PICTURE_ID
     *
     * @mbggenerated
     */
    public void setPictureId(Integer pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.RESOURCE_ID
     *
     * @return the value of TOM_ROLLING_PICTURE.RESOURCE_ID
     *
     * @mbggenerated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.RESOURCE_ID
     *
     * @param resourceId the value for TOM_ROLLING_PICTURE.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.PICTURE_CATEGORY
     *
     * @return the value of TOM_ROLLING_PICTURE.PICTURE_CATEGORY
     *
     * @mbggenerated
     */
    public String getPictureCategory() {
        return pictureCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.PICTURE_CATEGORY
     *
     * @param pictureCategory the value for TOM_ROLLING_PICTURE.PICTURE_CATEGORY
     *
     * @mbggenerated
     */
    public void setPictureCategory(String pictureCategory) {
        this.pictureCategory = pictureCategory == null ? null : pictureCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @return the value of TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @param pictureUrl the value for TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.RELEASE_TIME
     *
     * @return the value of TOM_ROLLING_PICTURE.RELEASE_TIME
     *
     * @mbggenerated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.RELEASE_TIME
     *
     * @param releaseTime the value for TOM_ROLLING_PICTURE.RELEASE_TIME
     *
     * @mbggenerated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.VIEW_COUNT
     *
     * @return the value of TOM_ROLLING_PICTURE.VIEW_COUNT
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.VIEW_COUNT
     *
     * @param viewCount the value for TOM_ROLLING_PICTURE.VIEW_COUNT
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.IS_RELEASE
     *
     * @return the value of TOM_ROLLING_PICTURE.IS_RELEASE
     *
     * @mbggenerated
     */
    public String getIsRelease() {
        return isRelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.IS_RELEASE
     *
     * @param isRelease the value for TOM_ROLLING_PICTURE.IS_RELEASE
     *
     * @mbggenerated
     */
    public void setIsRelease(String isRelease) {
        this.isRelease = isRelease == null ? null : isRelease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.IS_TOP
     *
     * @return the value of TOM_ROLLING_PICTURE.IS_TOP
     *
     * @mbggenerated
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.IS_TOP
     *
     * @param isTop the value for TOM_ROLLING_PICTURE.IS_TOP
     *
     * @mbggenerated
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop == null ? null : isTop.trim();
    }


    public String getAdmins() {
		return admins;
	}

	public void setAdmins(String admins) {
		this.admins = admins;
	}

	public String getResourceName() {
		return resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.CREATER
     *
     * @return the value of TOM_ROLLING_PICTURE.CREATER
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.CREATER
     *
     * @param creater the value for TOM_ROLLING_PICTURE.CREATER
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.CREATE_TIME
     *
     * @return the value of TOM_ROLLING_PICTURE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.CREATE_TIME
     *
     * @param createTime the value for TOM_ROLLING_PICTURE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.OPERATOR
     *
     * @return the value of TOM_ROLLING_PICTURE.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.OPERATOR
     *
     * @param operator the value for TOM_ROLLING_PICTURE.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.UPDATE_TIME
     *
     * @return the value of TOM_ROLLING_PICTURE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.UPDATE_TIME
     *
     * @param updateTime the value for TOM_ROLLING_PICTURE.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_ROLLING_PICTURE.DELETED
     *
     * @return the value of TOM_ROLLING_PICTURE.DELETED
     *
     * @mbggenerated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_ROLLING_PICTURE.DELETED
     *
     * @param deleted the value for TOM_ROLLING_PICTURE.DELETED
     *
     * @mbggenerated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_ROLLING_PICTURE.PICTURE_URL
     *
     * @mbggenerated
     */
	@FormParam("pictureUrlEn")
    private String pictureUrlEn;



	public String getPictureUrlEn() {
		return pictureUrlEn;
	}

	public void setPictureUrlEn(String pictureUrlEn) {
		this.pictureUrlEn = pictureUrlEn;
	}

	public String getEmpIds() {
		return empIds;
	}

	public void setEmpIds(String empIds) {
		this.empIds = empIds;
	}

	public List<Map<String, String>> getEmps() {
		return emps;
	}

	public void setEmps(List<Map<String, String>> emps) {
		this.emps = emps;
	}

	public String getIsRollingAllEmp() {
		return isRollingAllEmp;
	}

	public void setIsRollingAllEmp(String isRollingAllEmp) {
		this.isRollingAllEmp = isRollingAllEmp;
	}
    
}