package com.chinamobo.ue.activity.dao;

import com.chinamobo.ue.activity.common.BaseDao;
import com.chinamobo.ue.activity.entity.TomActivityExapInfo;

public interface TomActivityExapInfoMapper {//extends BaseDao<TomActivityExapInfo>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer retakingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    int insert(TomActivityExapInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    int insertSelective(TomActivityExapInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    TomActivityExapInfo selectByPrimaryKey(Integer retakingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomActivityExapInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_EXAM_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomActivityExapInfo record);
}