package com.chinamobo.ue.activity.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.activity.entity.TomActivityFees;
import com.chinamobo.ue.activity.entity.TomActivityFeesKey;
import com.chinamobo.ue.statistics.entity.TomActivityCostDetailStatistics;

public interface TomActivityFeesMapper {//extends BaseDao<TomActivityFeesKey>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    int insert(TomActivityFees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    int insertSelective(TomActivityFees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    TomActivityFees selectByPrimaryKey(TomActivityFeesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomActivityFees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomActivityFees record);
    
    
    List<TomActivityFees> selectByPrimaryParam(TomActivityFeesKey key);
    
    int deleteById(int freeId);

    /**
     * 
     * 功能描述：[伪删除]
     *
     * 创建者：JCX
     * 创建时间: 2016年6月2日 上午11:59:09
     * @param feesExample
     */
	void deleteByExample(TomActivityFees feesExample);
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_ACTIVITY_FEES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TomActivityFeesKey key);
    
    /**
     * 功能描述: [活动费用统计项目明细花费]
     * 创建者:LG
     * 创建时间：2016年6月6日 10：50
     * @param map
     */
    
    List<TomActivityCostDetailStatistics> selectByList(Map<Object,Object> map);
    
    int selectBycount(Map<Object,Object> map);
}
