package com.chinamobo.ue.activity.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.activity.entity.TomProjectResource;

public interface TomProjectResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TomProjectResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    int insert(TomProjectResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    int insertSelective(TomProjectResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    TomProjectResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomProjectResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tom_project_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomProjectResource record);

    TomProjectResource selectByResource(TomProjectResource resource);
    
    List<TomProjectResource> select(Map<Object, Object> map);
}