package com.chinamobo.ue.activity.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.activity.entity.TomProjectClassify;
import com.chinamobo.ue.common.entity.Tree;

public interface TomProjectClassifyMapper {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer classifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    int insert(TomProjectClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    int insertSelective(TomProjectClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    TomProjectClassify selectByPrimaryKey(Integer classifyId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    TomProjectClassify selectByPrimaryKeyEn(Integer classifyId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomProjectClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_CLASSIFY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomProjectClassify record);

    /**
     * 
     * 功能描述：[统计查询结果]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月1日 下午2:12:55
     * @param example
     * @return
     */
	int countByExample(Map<Object,Object> map);
	
	/**
     * 
     * 功能描述：[统计查询结果]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月1日 下午2:12:55
     * @param example
     * @return
     */
	int countByExampleEn(Map<Object,Object> map);
	
	/**
	 * 
	 * 功能描述：[分页查询]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:12:59
	 * @param map
	 * @return
	 */
	List<TomProjectClassify> selectListByPage(Map<Object, Object> map);
	
	/**
	 * 
	 * 功能描述：[分页查询]En
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:12:59
	 * @param map
	 * @return
	 */
	List<TomProjectClassify> selectListByPageEn(Map<Object, Object> map);
	
	/**
	 * 
	 * 功能描述：[查询所有]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:16:50
	 * @return
	 */
	List<TomProjectClassify> selectAll();
	
	/**
	 * 
	 * 功能描述：[查询所有]En
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:16:50
	 * @return
	 */
	List<TomProjectClassify> selectAllEn();
	
	/**
	 * 
	 * 功能描述：[获取父节点]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:13:03
	 * @param parentClassifyId
	 * @return
	 */
	TomProjectClassify getParent(Integer parentClassifyId);
	
	/**
	 * 
	 * 功能描述：[获取父节点]En
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:13:03
	 * @param parentClassifyId
	 * @return
	 */
	TomProjectClassify getParentEn(Integer parentClassifyId);


	/**
	 * 
	 * 功能描述：[根据父节点查询]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:13:07
	 * @param classifyId
	 * @return
	 */
	List<TomProjectClassify> selectByParentId(int classifyId);
	
	/**
	 * 
	 * 功能描述：[根据父节点查询]En
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月1日 下午2:13:07
	 * @param classifyId
	 * @return
	 */
	List<TomProjectClassify> selectByParentIdEn(int classifyId);


	/**
	 * 
	 * 功能描述：[根据多个id查询]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月8日 下午1:07:25
	 * @param classifyIds
	 * @return
	 */
	List<TomProjectClassify> selectByIds(Map<Object, Object> map);
	
	List<TomProjectClassify> selectByIdsEn(Map<Object, Object> map);

	List<Tree> selectClassifyAsTree();
	
	List<Tree> selectClassifyAsTreeEn();
	/**
	 * 
	 * 功能描述：查询所有分类
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月18日下午3:49:27
	 * @param map
	 * @return
	 */
	List<TomProjectClassify> selectListByPageAll(Map<Object, Object> map);
	
	/**
	 * 
	 * 功能描述：查询所有分类En
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月18日下午3:49:27
	 * @param map
	 * @return
	 */
	List<TomProjectClassify> selectListByPageAllEn(Map<Object, Object> map);
	
	/**
	 * 
	 * 功能描述：查询所有分类数据
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月18日下午3:51:29
	 * @param map
	 * @return
	 */
	int countByExampleAll(Map<Object,Object> map);
	
	/**
	 * 
	 * 功能描述：查询所有分类数据En
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月18日下午3:51:29
	 * @param map
	 * @return
	 */
	int countByExampleAllEn(Map<Object,Object> map);

	/**
	 * 
	 * 功能描述：[根据课程id查询分类]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月12日 上午10:31:42
	 * @param courseId
	 * @return
	 */
	List<TomProjectClassify> selectByProjectId(int courseId);
	
	/**
	 * 
	 * 功能描述：[根据课程id查询分类]En
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月12日 上午10:31:42
	 * @param courseId
	 * @return
	 */
	List<TomProjectClassify> selectByProjectIdEn(int courseId);
	/**
	 * 查找项目所有分类
	 */
	List<TomProjectClassify> selectAllProject();
	//根据活动选项目
    List<TomProjectClassify> selectByActivity(int activityId);
}