package com.chinamobo.ue.activity.dao;

import java.util.List;

import com.chinamobo.ue.activity.common.BaseDao;
import com.chinamobo.ue.activity.entity.TomTaskCoursesRelation;
import com.chinamobo.ue.activity.entity.TomTaskCoursesRelationKey;

public interface TomTaskCoursesRelationMapper {//extends BaseDao<TomTaskCoursesRelationKey>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    int deleteByPrimaryKey(TomTaskCoursesRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    int insert(TomTaskCoursesRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    int insertSelective(TomTaskCoursesRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    TomTaskCoursesRelation selectByPrimaryKey(TomTaskCoursesRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    int updateByPrimaryKeySelective(TomTaskCoursesRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_COURSES_RELATION
     *
     * @mbggenerated Thu Mar 10 12:27:25 CST 2016
     */
    int updateByPrimaryKey(TomTaskCoursesRelation record);

	TomTaskCoursesRelation selectByCourseId(Integer id);
	
	List<TomTaskCoursesRelation> selectByPackageId(Integer packageId);
}