package com.chinamobo.ue.activity.dao;

import java.util.List;

import com.chinamobo.ue.activity.entity.TomTaskCoursesRelation;
import com.chinamobo.ue.activity.entity.TomTaskExamPaperRelation;
import com.chinamobo.ue.activity.entity.TomTaskExamPaperRelationKey;

public interface TomTaskExamPaperRelationMapper {//extends BaseDao<TomTaskExamPaperRelationKey>{

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TomTaskExamPaperRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    int insert(TomTaskExamPaperRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    int insertSelective(TomTaskExamPaperRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    TomTaskExamPaperRelation selectByPrimaryKey(TomTaskExamPaperRelationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomTaskExamPaperRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_TASK_EXAM_RELATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomTaskExamPaperRelation record);

	List<TomTaskExamPaperRelation> selectByPackageId(Integer packageId);

	/**
	 * 
	 * 功能描述：[查询任务包关联试卷数量]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年6月3日 下午12:00:19
	 * @return
	 */
	int countByExample(int examPaperId);
}