package com.chinamobo.ue.exam.dao;

import java.util.List;

import com.chinamobo.ue.exam.entity.TomExamQuestion;
import com.chinamobo.ue.exam.entity.TomTopic;

public interface TomExamQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_QUESTION
     *
     * @mbggenerated
     */
    int insert(TomExamQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_QUESTION
     *
     * @mbggenerated
     */
    int insertSelective(TomExamQuestion record);

    /**
     * 
     * 功能描述：[查询试卷下所有题库关联]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月5日 下午4:00:32
     * @param examPaperId
     * @return
     */
	List<TomExamQuestion> selectByExamPaperId(Integer examPaperId);

	/**
	 * 
	 * 功能描述：[查询试卷题库关联]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月5日 下午3:59:04
	 * @param example
	 * @return
	 */
	TomExamQuestion selectByExample(TomExamQuestion example);
	
	int deleteAll(Integer examPaperId);

	/**
	 * 
	 * 功能描述：[根据条件查询关联]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月22日 下午4:51:27
	 * @param example
	 * @return
	 */
	List<TomExamQuestion> selectListByExample(TomExamQuestion example);
	/**
	 * 
	 * 功能描述：[查询所有考试所有题目]
	 * 创建者：Acemon
	 * 创建时间：2017年7月28日
	 */
	List<TomExamQuestion> selectAll();

}