package com.chinamobo.ue.exam.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.course.entity.TomCourseClassify;
import com.chinamobo.ue.exam.dto.ExamDto;
import com.chinamobo.ue.exam.entity.TomExam;
import com.chinamobo.ue.exam.entity.TomExamPaper;
import com.chinamobo.ue.statistics.entity.ExamAnswerDto;
import com.chinamobo.ue.statistics.entity.TomExamEmployeeStatistics;
import com.chinamobo.ue.statistics.entity.TomExamStatistics;

public interface TomExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    int insert(TomExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    int insertSelective(TomExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    TomExam selectByPrimaryKey(Integer examId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomExam record);

    
	/**
	 * 功能描述：[查询所有]
	 *
	 * 创建者：xjw
	 * 创建时间: 2016年3月4日 下午3:47:42
	 * @return
	 */
	List<TomExam> selectAll();

	/**
	 * 功能描述：[统计查询数目]
	 *
	 * 创建者：xjw
	 * 创建时间: 2016年3月4日 下午4:02:57
	 * @param map
	 * @return
	 */
	int countByExample(Map<Object, Object> map);
	
    /**
     * 功能描述：[考试查询]
     *
     * 创建者：xjw
     * 创建时间: 2016年3月4日 下午2:47:43
     * @param pageNum
     * @param pageSize
     * @param examname
     * @return
     */
    List<TomExam> findList(Map<Object,Object> map);
    
    /**
     * 功能描述：[查询课程]
     *
     * 创建者：WangLg
     * 创建时间: 2016年3月15日 下午5:47:23
     * @return
     */
    List<TomExamPaper> findExampaper();
    
    /**
     * 
     * 功能描述：[查询用户的考试数量]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月21日 上午11:25:52
     * @param map
     * @return
     */
    int countByUser(Map<Object, Object> map);
    
    /**
     * 
     * 功能描述：[查询用户的考试列表]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月21日 上午11:26:05
     * @param map
     * @return
     */
    List<TomExam> selectByUser(Map<Object,Object> map);

    /**
     * 
     * 功能描述：[统计我的考试数量]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月25日 上午9:37:58
     * @param queryMap
     * @return
     */
	int countMyExam(Map<Object, Object> queryMap);

	/**
	 * 
	 * 功能描述：[查询我的考试列表]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月25日 上午9:38:08
	 * @param queryMap
	 * @return
	 */
	List<TomExam> selectMyExam(Map<Object, Object> queryMap);
	
	List<TomExam>selectByPackageId(int packageId);
	
	List<TomExam> selectByExamPaperId(Integer examPaperId);
	
   int countByUserGlobel(Map<Object, Object> map);
   
   List<TomExam> selectByUserGlobel(Map<Object,Object> map);
   
   /**
    * 功能描述:[考试统计列表分页查询]
    * 创建人：LG
    * 创建时间：2016年6月4日
    * @param map
    */
   int selectBycount(Map<Object,Object> map);
   
   List<TomExamStatistics> selectByList(Map<Object,Object> map);
   /**
    * 功能描述：[根据codes查询]
    * 创建人：Acemon
    * 创建时间：2017年2月13号
    */
   List<TomExamStatistics> selectByCodes(Map<Object,Object> map);
   /**
    * 功能描述:[考试统计相信列表分页查询]
    * 创建人：LG
    * 创建时间：2016年6月4日
    * @param map
    */
   int selectEmployeeBycount(Map<Object,Object> map);
   
   int selectRealEmployeeBycount(Map<Object,Object> map);
   
   List<TomExamEmployeeStatistics> selectEmployeeByList(Map<Object,Object> map);
   
   List<TomExamEmployeeStatistics> selectRealEmployeeByList(Map<Object,Object> map);

   /**
    * 
    * 功能描述：[查询答题详情统计]
    *
    * 创建者：JCX
    * 创建时间: 2016年7月25日 下午4:32:05
    * @param examId
    * @return
    */
	List<ExamAnswerDto> selectAnswerDto(int examId);
	
	List<ExamDto> selectempExamlistBypage(Map<Object,Object> map);
	int countempExamlist(Map<Object,Object> map);
}