package com.chinamobo.ue.exam.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.exam.entity.TomExamAnswerDetails;

public interface TomExamAnswerDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_ANSWER_DETAILS
     *
     * @mbggenerated
     */
    int insert(TomExamAnswerDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_EXAM_ANSWER_DETAILS
     *
     * @mbggenerated
     */
    int insertSelective(TomExamAnswerDetails record);

	/**
	 * 
	 * 功能描述：[更新]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月23日 上午10:57:56
	 * @param record
	 * @return
	 */
	int updateSelective(TomExamAnswerDetails record);
	
	/**
	 * 
	 * 功能描述：[根据条件查询单个答题详情]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月6日 下午12:48:58
	 * @param record
	 * @return
	 */
	TomExamAnswerDetails selectOneByExample(TomExamAnswerDetails record);

	/**
	 * 
	 * 功能描述：[删除答题详情]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月20日 上午10:16:17
	 * @param answerDetails
	 */
	void deleteByExample(TomExamAnswerDetails answerDetails);

	/**
	 * 
	 * 功能描述：[查询]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月20日 下午3:10:52
	 * @param examAnswerDetailsExample
	 * @return
	 */
	List<TomExamAnswerDetails> selectByExample(
			TomExamAnswerDetails examAnswerDetailsExample);

	/**
	 * 
	 * 功能描述：[更新未审阅的成绩]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月20日 下午4:10:50
	 * @param record
	 */
	void updateGrade(TomExamAnswerDetails record);
	
	List<TomExamAnswerDetails> selectByCode(TomExamAnswerDetails examAnswerDetailsExample);
}