package com.chinamobo.ue.exam.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.common.entity.Tree;
import com.chinamobo.ue.exam.entity.TomQuestionClassification;

public interface TomQuestionClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer questionClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    int insert(TomQuestionClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    int insertSelective(TomQuestionClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    TomQuestionClassification selectByPrimaryKey(Integer questionClassificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomQuestionClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_QUESTION_CLASSIFICATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomQuestionClassification record);
    
    List<TomQuestionClassification> findList(Map<Object,Object> map);
    
    List<TomQuestionClassification> selectPage(Map<Object,Object> map);
    
    int count(Map<Object,Object> map);

    /**
     * 
     * 功能描述：[查询列表]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月7日 下午3:46:22
     * @param example
     * @return
     */
	List<TomQuestionClassification> selectListByExample(TomQuestionClassification example);

	/**
	 * 
	 * 功能描述：[计算总记录数]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月7日 下午3:53:48
	 * @param map
	 * @return
	 */
	int countByMap(Map<Object, Object> map);

	/**
	 * 
	 * 功能描述：[分页查询]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月7日 下午3:57:33
	 * @param map
	 * @return
	 */
	List<TomQuestionClassification> selectListByPage(Map<Object, Object> map);

	/**
	 * 
	 * 功能描述：[查询分类树]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月7日 下午5:01:37
	 * @return
	 */
	List<Tree> selectClassifyAsTree();

	List<TomQuestionClassification> selectList();

}