package com.chinamobo.ue.exam.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.exam.entity.TomRetakingExam;

public interface TomRetakingExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    int insert(TomRetakingExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    int insertSelective(TomRetakingExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    TomRetakingExam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomRetakingExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_RETAKING_EXAM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomRetakingExam record);

    /**
     * 
     * 功能描述：[查询补考]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月23日 下午3:56:19
     * @param retakingExample
     * @return
     */
	TomRetakingExam selectOneByExample(TomRetakingExam retakingExample);

	/**
	 * 
	 * 功能描述：[查询所有补考]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月31日 下午1:53:36
	 * @param example
	 * @return
	 */
	List<TomRetakingExam> selectListByExample(TomRetakingExam example);
	
	TomRetakingExam selectTimeByExample(TomRetakingExam example);
	/**
	 * 
	 * 功能描述：[删除课程补考]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月12日 下午4:33:41
	 * @param examId
	 */
	void deleteByExamId(Integer examId);

	/**
	 * 
	 * 功能描述：[根据时间得到此时间点所在的补考]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年4月19日 下午12:43:19
	 * @param map
	 * @return
	 */
	List<TomRetakingExam> selectByTime(Map<Object, Object> map);
	/**
	 * 
	 * 功能描述：[查全部数据]
	 * 创建者：Acemon
	 * 创建时间：2017年7月28日
	 */
	List<TomRetakingExam> selectAll();

}