package com.chinamobo.ue.course.dto;

import java.util.Date;
import java.util.List;

import javax.ws.rs.FormParam;

public class TomCourseWithSection {

	@FormParam("courseId")
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("courseNumber")
    private String courseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_NAME
     *
     * @mbggenerated
     */
	@FormParam("courseName")
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_ONLINE
     *
     * @mbggenerated
     */
	@FormParam("courseOnline")
    private String courseOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_INTRODUCTION
     *
     * @mbggenerated
     */
	@FormParam("courseIntroduction")
    private String courseIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_TYPE
     *
     * @mbggenerated
     */
	@FormParam("courseType")
    private String courseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.E_CURRENCY
     *
     * @mbggenerated
     */
	@FormParam("eCurrency")
    private Integer eCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_GRADE_DIMENSIONS
     *
     * @mbggenerated
     */
	@FormParam("courseGradeDimensions")
    private String courseGradeDimensions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.LECTURER_GRADE_DIMENSIONS
     *
     * @mbggenerated
     */
	@FormParam("lecturerGradeDimensions")
    private String lecturerGradeDimensions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.LECTURERS
     *
     * @mbggenerated
     */
	@FormParam("lecturers")
    private String lecturers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_IMG
     *
     * @mbggenerated
     */
	@FormParam("courseImg")
    private String courseImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_DOWNLOADABLE
     *
     * @mbggenerated
     */
	@FormParam("courseDownloadable")
    private String courseDownloadable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.IS_EXCELLENT_COURSE
     *
     * @mbggenerated
     */
	@FormParam("isExcellentCourse")
    private String isExcellentCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.STATUS
     *
     * @mbggenerated
     */
	@FormParam("status")
    private String status;
	
	@FormParam("btnName")
    private String btnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.OPEN_COMMENT
     *
     * @mbggenerated
     */
	@FormParam("openComment")
    private String openComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.OPEN_COURSE
     *
     * @mbggenerated
     */
	@FormParam("openCourse")
    private String openCourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.ADMINS
     *
     * @mbggenerated
     */
	@FormParam("admins")
    private String admins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.VIEWERS
     *
     * @mbggenerated
     */
	@FormParam("viewers")
    private Integer viewers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.THUMB_UP_COUNT
     *
     * @mbggenerated
     */
	@FormParam("thumbUpCount")
    private Integer thumbUpCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COMMENT_COUNT
     *
     * @mbggenerated
     */
	@FormParam("commentCount")
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.RATETIMES
     *
     * @mbggenerated
     */
	@FormParam("ratetimes")
    private Integer ratetimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_AVERAGE
     *
     * @mbggenerated
     */
	@FormParam("courseAverage")
    private Double courseAverage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.TOT_SCORE
     *
     * @mbggenerated
     */
	@FormParam("totScore")
    private Double totScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.LECTURER_AVERAGE
     *
     * @mbggenerated
     */
	@FormParam("lecturerAverage")
    private Double lecturerAverage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.COURSE_TIMES
     *
     * @mbggenerated
     */
	@FormParam("courseTimes")
    private Double courseTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.SIGN_IN_TWO_DIMENSION_CODE
     *
     * @mbggenerated
     */
	@FormParam("signInTwoDimensionCode")
    private String signInTwoDimensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.GRADE_TWO_DIMENSION_CODE
     *
     * @mbggenerated
     */
	@FormParam("gradeTwoDimensionCode")
    private String gradeTwoDimensionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("operator")
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSES.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSES.COURSE_ID
     *
     * @return the value of TOM_COURSES.COURSE_ID
     *
     * @mbggenerated
     */
	@FormParam("learnedNum")
	private Integer learnedNum;
	
	@FormParam("sectionName[]")
	private List<String> sectionNameList;
	
	@FormParam("sectionAddress[]")
	private List<String> sectionAddressList;

	@FormParam("empIds[]")
	private List<String> empIds;
	
	public Integer getCourseId() {
		return courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getCourseNumber() {
		return courseNumber;
	}

	public void setCourseNumber(String courseNumber) {
		this.courseNumber = courseNumber;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getCourseOnline() {
		return courseOnline;
	}

	public void setCourseOnline(String courseOnline) {
		this.courseOnline = courseOnline;
	}

	public String getCourseIntroduction() {
		return courseIntroduction;
	}

	public void setCourseIntroduction(String courseIntroduction) {
		this.courseIntroduction = courseIntroduction;
	}

	public String getCourseType() {
		return courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	public Integer geteCurrency() {
		return eCurrency;
	}

	public void seteCurrency(Integer eCurrency) {
		this.eCurrency = eCurrency;
	}

	public String getCourseGradeDimensions() {
		return courseGradeDimensions;
	}

	public void setCourseGradeDimensions(String courseGradeDimensions) {
		this.courseGradeDimensions = courseGradeDimensions;
	}

	public String getLecturerGradeDimensions() {
		return lecturerGradeDimensions;
	}

	public void setLecturerGradeDimensions(String lecturerGradeDimensions) {
		this.lecturerGradeDimensions = lecturerGradeDimensions;
	}

	public String getLecturers() {
		return lecturers;
	}

	public void setLecturers(String lecturers) {
		this.lecturers = lecturers;
	}

	public String getCourseImg() {
		return courseImg;
	}

	public void setCourseImg(String courseImg) {
		this.courseImg = courseImg;
	}

	public String getCourseDownloadable() {
		return courseDownloadable;
	}

	public void setCourseDownloadable(String courseDownloadable) {
		this.courseDownloadable = courseDownloadable;
	}

	public String getIsExcellentCourse() {
		return isExcellentCourse;
	}

	public void setIsExcellentCourse(String isExcellentCourse) {
		this.isExcellentCourse = isExcellentCourse;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBtnName() {
		return btnName;
	}

	public void setBtnName(String btnName) {
		this.btnName = btnName;
	}

	public String getOpenComment() {
		return openComment;
	}

	public void setOpenComment(String openComment) {
		this.openComment = openComment;
	}

	public String getOpenCourse() {
		return openCourse;
	}

	public void setOpenCourse(String openCourse) {
		this.openCourse = openCourse;
	}

	public String getAdmins() {
		return admins;
	}

	public void setAdmins(String admins) {
		this.admins = admins;
	}

	public Integer getViewers() {
		return viewers;
	}

	public void setViewers(Integer viewers) {
		this.viewers = viewers;
	}

	public Integer getThumbUpCount() {
		return thumbUpCount;
	}

	public void setThumbUpCount(Integer thumbUpCount) {
		this.thumbUpCount = thumbUpCount;
	}

	public Integer getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(Integer commentCount) {
		this.commentCount = commentCount;
	}

	public Integer getRatetimes() {
		return ratetimes;
	}

	public void setRatetimes(Integer ratetimes) {
		this.ratetimes = ratetimes;
	}

	public Double getCourseAverage() {
		return courseAverage;
	}

	public void setCourseAverage(Double courseAverage) {
		this.courseAverage = courseAverage;
	}

	public Double getTotScore() {
		return totScore;
	}

	public void setTotScore(Double totScore) {
		this.totScore = totScore;
	}

	public Double getLecturerAverage() {
		return lecturerAverage;
	}

	public void setLecturerAverage(Double lecturerAverage) {
		this.lecturerAverage = lecturerAverage;
	}

	public Double getCourseTimes() {
		return courseTimes;
	}

	public void setCourseTimes(Double courseTimes) {
		this.courseTimes = courseTimes;
	}

	public String getSignInTwoDimensionCode() {
		return signInTwoDimensionCode;
	}

	public void setSignInTwoDimensionCode(String signInTwoDimensionCode) {
		this.signInTwoDimensionCode = signInTwoDimensionCode;
	}

	public String getGradeTwoDimensionCode() {
		return gradeTwoDimensionCode;
	}

	public void setGradeTwoDimensionCode(String gradeTwoDimensionCode) {
		this.gradeTwoDimensionCode = gradeTwoDimensionCode;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getLearnedNum() {
		return learnedNum;
	}

	public void setLearnedNum(Integer learnedNum) {
		this.learnedNum = learnedNum;
	}

	public List<String> getSectionNameList() {
		return sectionNameList;
	}

	public void setSectionNameList(List<String> sectionNameList) {
		this.sectionNameList = sectionNameList;
	}

	public List<String> getSectionAddressList() {
		return sectionAddressList;
	}

	public void setSectionAddressList(List<String> sectionAddressList) {
		this.sectionAddressList = sectionAddressList;
	}

	public List<String> getEmpIds() {
		return empIds;
	}

	public void setEmpIds(List<String> empIds) {
		this.empIds = empIds;
	}
	
	
}
