package com.chinamobo.ue.exam.entity;

import java.util.Date;

public class TomExamEmpAllocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_EMP_ALLOCATION.EXAM_ID
     *
     * @mbggenerated
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_EMP_ALLOCATION.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_EMP_ALLOCATION.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_EMP_ALLOCATION.EXAM_ID
     *
     * @return the value of TOM_EXAM_EMP_ALLOCATION.EXAM_ID
     *
     * @mbggenerated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_EMP_ALLOCATION.EXAM_ID
     *
     * @param examId the value for TOM_EXAM_EMP_ALLOCATION.EXAM_ID
     *
     * @mbggenerated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_EMP_ALLOCATION.CODE
     *
     * @return the value of TOM_EXAM_EMP_ALLOCATION.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_EMP_ALLOCATION.CODE
     *
     * @param code the value for TOM_EXAM_EMP_ALLOCATION.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_EMP_ALLOCATION.CREATE_TIME
     *
     * @return the value of TOM_EXAM_EMP_ALLOCATION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_EMP_ALLOCATION.CREATE_TIME
     *
     * @param createTime the value for TOM_EXAM_EMP_ALLOCATION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}