package com.chinamobo.ue.exam.entity;

import java.util.Date;
import java.util.List;

import javax.ws.rs.FormParam;

public class TomExam {
	
	
	@FormParam("parentProjectClassifyName")
    private String parentProjectClassifyName;
	
    public String getParentProjectClassifyName() {
		return parentProjectClassifyName;
	}

	public void setParentProjectClassifyName(String parentProjectClassifyName) {
		this.parentProjectClassifyName = parentProjectClassifyName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
	@FormParam("examId")
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("examNumber")
    private String examNumber;
	
	

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_NAME
     *
     * @mbggenerated
     */
	@FormParam("examName")
    private String examName;

	@FormParam("examNameEn")
    private String examNameEn;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date beginTime;

    private Date endTime;
    @FormParam("isEN")
    private String isEN;
    @FormParam("isCN")
	private String isCN;
	
	
	public String getIsEN() {
		return isEN;
	}

	public void setIsEN(String isEN) {
		this.isEN = isEN;
	}

	public String getIsCN() {
		return isCN;
	}

	public void setIsCN(String isCN) {
		this.isCN = isCN;
	}

	@FormParam("beginTimeS")
	private String beginTimeS;

	@FormParam("endTimeS")
	private String endTimeS;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
	@FormParam("examPaperId")
    private Integer examPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_TIME
     *
     * @mbggenerated
     */
	@FormParam("examTime")
    private Integer examTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.RETAKING_EXAM_COUNT
     *
     * @mbggenerated
     */
	@FormParam("retakingExamCount")
    private Integer retakingExamCount;

	private Integer remainingCount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.EXAM_TYPE
     *
     * @mbggenerated
     */
	@FormParam("examType")
    private String examType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.OFFLINE_EXAM
     *
     * @mbggenerated
     */
	@FormParam("offlineExam")
    private String offlineExam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.ADMIN_ID
     *
     * @mbggenerated
     */
	@FormParam("admins")
	private String admins;
	@FormParam("adminNames")
	private String adminNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
    private String creator;
	
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.LAST_OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("lastOperator")
    private String lastOperator;
	
    private String lastOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

	@FormParam("testQuestionCount")
	private Integer testQuestionCount;
	
	@FormParam("passMark")
    private Integer passMark;
	
	@FormParam("fullMark")
    private Integer fullMark;
	
	@FormParam("examPaperPicture")
    private String examPaperPicture;
	@FormParam("examPaperPictureEn")
	private String examPaperPictureEn;
	
	public String getExamPaperPictureEn() {
		return examPaperPictureEn;
	}

	public void setExamPaperPictureEn(String examPaperPictureEn) {
		this.examPaperPictureEn = examPaperPictureEn;
	}

	@FormParam("examAddress")
	private String examAddress;
	
	@FormParam("examAddressEn")
	private String examAddressEn;
	
	@FormParam("passEb")
    private Integer passEb;
	//考试状态, 用于我的考试显示状态
	private String examState;
	//考试详细状态, 用于我的考试跳转详情的判断
	private String examDetailState;

	private String totalPoints;
	
	@FormParam("rbeginTime[]")
	private List<String> rbeginTime;
	
	@FormParam("rendTime[]")
	private List<String> rendTime;
	
	@FormParam("empIds[]")
	private List<String> empIds;
	@FormParam("empNames[]")
	private List<String> empNames;
	private List<String> cityname;
	private List<String> deptname;
	
	
	private String showQualifiedStandard;
	private String preStatus;
	@FormParam("parentClassifyId")
	private String parentClassifyId;
	
	

	public String getParentClassifyId() {
		return parentClassifyId;
	}

	public void setParentClassifyId(String parentClassifyId) {
		this.parentClassifyId = parentClassifyId;
	}

	public String getExamDetailState() {
		return examDetailState;
	}

	public void setExamDetailState(String examDetailState) {
		this.examDetailState = examDetailState;
	}

	public String getPreStatus() {
		return preStatus;
	}

	public String getShowQualifiedStandard() {
		return showQualifiedStandard;
	}

	public void setShowQualifiedStandard(String showQualifiedStandard) {
		this.showQualifiedStandard = showQualifiedStandard;
	}

	public void setPreStatus(String preStatus) {
		this.preStatus = preStatus;
	}

	public List<String> getRbeginTime() {
		return rbeginTime;
	}

	public void setRbeginTime(List<String> rbeginTime) {
		this.rbeginTime = rbeginTime;
	}

	public List<String> getRendTime() {
		return rendTime;
	}

	public void setRendTime(List<String> rendTime) {
		this.rendTime = rendTime;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_ID
     *
     * @return the value of TOM_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_ID
     *
     * @param examId the value for TOM_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_NUMBER
     *
     * @return the value of TOM_EXAM.EXAM_NUMBER
     *
     * @mbggenerated
     */
    public String getExamNumber() {
        return examNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_NUMBER
     *
     * @param examNumber the value for TOM_EXAM.EXAM_NUMBER
     *
     * @mbggenerated
     */
    public void setExamNumber(String examNumber) {
        this.examNumber = examNumber == null ? null : examNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_NAME
     *
     * @return the value of TOM_EXAM.EXAM_NAME
     *
     * @mbggenerated
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_NAME
     *
     * @param examName the value for TOM_EXAM.EXAM_NAME
     *
     * @mbggenerated
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.BEGIN_TIME
     *
     * @return the value of TOM_EXAM.BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_PAPER_ID
     *
     * @return the value of TOM_EXAM.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_PAPER_ID
     *
     * @param examPaperId the value for TOM_EXAM.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_TIME
     *
     * @return the value of TOM_EXAM.EXAM_TIME
     *
     * @mbggenerated
     */
    public Integer getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_TIME
     *
     * @param examTime the value for TOM_EXAM.EXAM_TIME
     *
     * @mbggenerated
     */
    public void setExamTime(Integer examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.RETAKING_EXAM_COUNT
     *
     * @return the value of TOM_EXAM.RETAKING_EXAM_COUNT
     *
     * @mbggenerated
     */
    public Integer getRetakingExamCount() {
        return retakingExamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.RETAKING_EXAM_COUNT
     *
     * @param retakingExamCount the value for TOM_EXAM.RETAKING_EXAM_COUNT
     *
     * @mbggenerated
     */
    public void setRetakingExamCount(Integer retakingExamCount) {
        this.retakingExamCount = retakingExamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.EXAM_TYPE
     *
     * @return the value of TOM_EXAM.EXAM_TYPE
     *
     * @mbggenerated
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.EXAM_TYPE
     *
     * @param examType the value for TOM_EXAM.EXAM_TYPE
     *
     * @mbggenerated
     */
    public void setExamType(String examType) {
        this.examType = examType == null ? null : examType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.OFFLINE_EXAM
     *
     * @return the value of TOM_EXAM.OFFLINE_EXAM
     *
     * @mbggenerated
     */
    public String getOfflineExam() {
        return offlineExam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.OFFLINE_EXAM
     *
     * @param offlineExam the value for TOM_EXAM.OFFLINE_EXAM
     *
     * @mbggenerated
     */
    public void setOfflineExam(String offlineExam) {
        this.offlineExam = offlineExam == null ? null : offlineExam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.CREATE_TIME
     *
     * @return the value of TOM_EXAM.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.CREATE_TIME
     *
     * @param createTime the value for TOM_EXAM.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.CREATOR
     *
     * @return the value of TOM_EXAM.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.CREATOR
     *
     * @param creator the value for TOM_EXAM.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.LAST_OPERATOR
     *
     * @return the value of TOM_EXAM.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public String getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.LAST_OPERATOR
     *
     * @param lastOperator the value for TOM_EXAM.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public void setLastOperator(String lastOperator) {
        this.lastOperator = lastOperator == null ? null : lastOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM.UPDATE_TIME
     *
     * @return the value of TOM_EXAM.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM.UPDATE_TIME
     *
     * @param updateTime the value for TOM_EXAM.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public Integer getTestQuestionCount() {
		return testQuestionCount;
	}

	public void setTestQuestionCount(Integer testQuestionCount) {
		this.testQuestionCount = testQuestionCount;
	}

	public Integer getPassMark() {
		return passMark;
	}

	public void setPassMark(Integer passMark) {
		this.passMark = passMark;
	}

	public Integer getFullMark() {
		return fullMark;
	}

	public void setFullMark(Integer fullMark) {
		this.fullMark = fullMark;
	}

	public String getExamPaperPicture() {
		return examPaperPicture;
	}

	public void setExamPaperPicture(String examPaperPicture) {
		this.examPaperPicture = examPaperPicture;
	}

	public String getExamAddress() {
		return examAddress;
	}

	public void setExamAddress(String examAddress) {
		this.examAddress = examAddress;
	}

	public Integer getPassEb() {
		return passEb;
	}

	public void setPassEb(Integer passEb) {
		this.passEb = passEb;
	}

	public String getExamState() {
		return examState;
	}

	public void setExamState(String examState) {
		this.examState = examState;
	}

	public String getTotalPoints() {
		return totalPoints;
	}

	public void setTotalPoints(String totalPoints) {
		this.totalPoints = totalPoints;
	}


	public String getBeginTimeS() {
		return beginTimeS;
	}

	public void setBeginTimeS(String beginTimeS) {
		this.beginTimeS = beginTimeS;
	}

	public String getEndTimeS() {
		return endTimeS;
	}

	public void setEndTimeS(String endTimeS) {
		this.endTimeS = endTimeS;
	}

	public Integer getRemainingCount() {
		return remainingCount;
	}

	public void setRemainingCount(Integer remainingCount) {
		this.remainingCount = remainingCount;
	}

	public String getAdmins() {
		return admins;
	}

	public void setAdmins(String admins) {
		this.admins = admins;
	}

	public String getAdminNames() {
		return adminNames;
	}

	public void setAdminNames(String adminNames) {
		this.adminNames = adminNames;
	}


	public List<String> getEmpIds() {
		return empIds;
	}

	public void setEmpIds(List<String> empIds) {
		this.empIds = empIds;
	}

	public List<String> getEmpNames() {
		return empNames;
	}

	public void setEmpNames(List<String> empNames) {
		this.empNames = empNames;
	}

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public String getLastOperatorId() {
		return lastOperatorId;
	}

	public void setLastOperatorId(String lastOperatorId) {
		this.lastOperatorId = lastOperatorId;
	}

	public List<String> getCityname() {
		return cityname;
	}

	public void setCityname(List<String> cityname) {
		this.cityname = cityname;
	}

	public List<String> getDeptname() {
		return deptname;
	}

	public void setDeptname(List<String> deptname) {
		this.deptname = deptname;
	}

	public String getExamNameEn() {
		return examNameEn;
	}

	public void setExamNameEn(String examNameEn) {
		this.examNameEn = examNameEn;
	}

	public String getExamAddressEn() {
		return examAddressEn;
	}

	public void setExamAddressEn(String examAddressEn) {
		this.examAddressEn = examAddressEn;
	}

    private int activityId;
    private String activityName;
	public int getActivityId() {
		return activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;

	}
    private String gradeState;

	public String getGradeState() {
		return gradeState;
	}

	public void setGradeState(String gradeState) {
		this.gradeState = gradeState;
	}
	private String status;


	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getActivityName() {
		return activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}
	
}
