package com.chinamobo.ue.exam.entity;

import java.util.Date;

import javax.ws.rs.FormParam;

public class TomExamPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
	@FormParam("examPaperId")
    private Integer examPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_PAPER_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("examPaperNumber")
	private String examPaperNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_PAPER_NAME
     *
     * @mbggenerated
     */
	@FormParam("examPaperName")
    private String examPaperName;
	
	@FormParam("examPaperNameEn")
    private String examPaperNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_PAPER_TYPE
     *
     * @mbggenerated
     */
	@FormParam("examPaperType")
    private String examPaperType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_PAPER_PICTURE
     *
     * @mbggenerated
     */
	@FormParam("examPaperPicture")
    private String examPaperPicture;
	
	@FormParam("examPaperPictureEn")
    private String examPaperPictureEn;

    public String getExamPaperPictureEn() {
		return examPaperPictureEn;
	}

	public void setExamPaperPictureEn(String examPaperPictureEn) {
		this.examPaperPictureEn = examPaperPictureEn;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.EXAM_TIME
     *
     * @mbggenerated
     */
	@FormParam("examTime")
    private Integer examTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.FULL_MARK
     *
     * @mbggenerated
     */
	@FormParam("fullMark")
    private Integer fullMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.PASS_MARK
     *
     * @mbggenerated
     */
	@FormParam("passMark")
    private Integer passMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.TEST_QUESTION_COUNT
     *
     * @mbggenerated
     */
	@FormParam("testQuestionCount")
    private Integer testQuestionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.PASS_EB
     *
     * @mbggenerated
     */
	@FormParam("passEb")
    private Integer passEb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.NOT_PASS_EB
     *
     * @mbggenerated
     */
	@FormParam("notPassEb")
    private Integer notPassEb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.SHOW_SCORE
     *
     * @mbggenerated
     */
	@FormParam("showScore")
    private String showScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.SHOW_QUALIFIED_STANDARD
     *
     * @mbggenerated
     */
	@FormParam("showQualifiedStandard")
    private String showQualifiedStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.IMMEDIATELY_SHOW
     *
     * @mbggenerated
     */
	@FormParam("immediatelyShow")
    private String immediatelyShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.ADMIN_ID
     *
     * @mbggenerated
     */
	@FormParam("admins")
	private String admins;
	@FormParam("adminNames")
	private String adminNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.CREATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("createTime")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
    private String creator;
	
	private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.LAST_OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("lastOperator")
    private String lastOperator;
	
	private String lastOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_PAPER.UPDATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("updateTime")
    private Date updateTime;
	
	private String sorts;

    public String getSorts() {
		return sorts;
	}

	public void setSorts(String sorts) {
		this.sorts = sorts;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_ID
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_ID
     *
     * @param examPaperId the value for TOM_EXAM_PAPER.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_NUMBER
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_PAPER_NUMBER
     *
     * @mbggenerated
     */
    public String getExamPaperNumber() {
        return examPaperNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_NUMBER
     *
     * @param examPaperNumber the value for TOM_EXAM_PAPER.EXAM_PAPER_NUMBER
     *
     * @mbggenerated
     */
    public void setExamPaperNumber(String examPaperNumber) {
        this.examPaperNumber = examPaperNumber == null ? null : examPaperNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_NAME
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_PAPER_NAME
     *
     * @mbggenerated
     */
    public String getExamPaperName() {
        return examPaperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_NAME
     *
     * @param examPaperName the value for TOM_EXAM_PAPER.EXAM_PAPER_NAME
     *
     * @mbggenerated
     */
    public void setExamPaperName(String examPaperName) {
        this.examPaperName = examPaperName == null ? null : examPaperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_TYPE
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_PAPER_TYPE
     *
     * @mbggenerated
     */
    public String getExamPaperType() {
        return examPaperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_TYPE
     *
     * @param examPaperType the value for TOM_EXAM_PAPER.EXAM_PAPER_TYPE
     *
     * @mbggenerated
     */
    public void setExamPaperType(String examPaperType) {
        this.examPaperType = examPaperType == null ? null : examPaperType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_PICTURE
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_PAPER_PICTURE
     *
     * @mbggenerated
     */
    public String getExamPaperPicture() {
        return examPaperPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_PAPER_PICTURE
     *
     * @param examPaperPicture the value for TOM_EXAM_PAPER.EXAM_PAPER_PICTURE
     *
     * @mbggenerated
     */
    public void setExamPaperPicture(String examPaperPicture) {
        this.examPaperPicture = examPaperPicture == null ? null : examPaperPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.EXAM_TIME
     *
     * @return the value of TOM_EXAM_PAPER.EXAM_TIME
     *
     * @mbggenerated
     */
    public Integer getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.EXAM_TIME
     *
     * @param examTime the value for TOM_EXAM_PAPER.EXAM_TIME
     *
     * @mbggenerated
     */
    public void setExamTime(Integer examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.FULL_MARK
     *
     * @return the value of TOM_EXAM_PAPER.FULL_MARK
     *
     * @mbggenerated
     */
    public Integer getFullMark() {
        return fullMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.FULL_MARK
     *
     * @param fullMark the value for TOM_EXAM_PAPER.FULL_MARK
     *
     * @mbggenerated
     */
    public void setFullMark(Integer fullMark) {
        this.fullMark = fullMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.PASS_MARK
     *
     * @return the value of TOM_EXAM_PAPER.PASS_MARK
     *
     * @mbggenerated
     */
    public Integer getPassMark() {
        return passMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.PASS_MARK
     *
     * @param passMark the value for TOM_EXAM_PAPER.PASS_MARK
     *
     * @mbggenerated
     */
    public void setPassMark(Integer passMark) {
        this.passMark = passMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.TEST_QUESTION_COUNT
     *
     * @return the value of TOM_EXAM_PAPER.TEST_QUESTION_COUNT
     *
     * @mbggenerated
     */
    public Integer getTestQuestionCount() {
        return testQuestionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.TEST_QUESTION_COUNT
     *
     * @param testQuestionCount the value for TOM_EXAM_PAPER.TEST_QUESTION_COUNT
     *
     * @mbggenerated
     */
    public void setTestQuestionCount(Integer testQuestionCount) {
        this.testQuestionCount = testQuestionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.PASS_EB
     *
     * @return the value of TOM_EXAM_PAPER.PASS_EB
     *
     * @mbggenerated
     */
    public Integer getPassEb() {
        return passEb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.PASS_EB
     *
     * @param passEb the value for TOM_EXAM_PAPER.PASS_EB
     *
     * @mbggenerated
     */
    public void setPassEb(Integer passEb) {
        this.passEb = passEb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.NOT_PASS_EB
     *
     * @return the value of TOM_EXAM_PAPER.NOT_PASS_EB
     *
     * @mbggenerated
     */
    public Integer getNotPassEb() {
        return notPassEb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.NOT_PASS_EB
     *
     * @param notPassEb the value for TOM_EXAM_PAPER.NOT_PASS_EB
     *
     * @mbggenerated
     */
    public void setNotPassEb(Integer notPassEb) {
        this.notPassEb = notPassEb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.SHOW_SCORE
     *
     * @return the value of TOM_EXAM_PAPER.SHOW_SCORE
     *
     * @mbggenerated
     */
    public String getShowScore() {
        return showScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.SHOW_SCORE
     *
     * @param showScore the value for TOM_EXAM_PAPER.SHOW_SCORE
     *
     * @mbggenerated
     */
    public void setShowScore(String showScore) {
        this.showScore = showScore == null ? null : showScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.SHOW_QUALIFIED_STANDARD
     *
     * @return the value of TOM_EXAM_PAPER.SHOW_QUALIFIED_STANDARD
     *
     * @mbggenerated
     */
    public String getShowQualifiedStandard() {
        return showQualifiedStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.SHOW_QUALIFIED_STANDARD
     *
     * @param showQualifiedStandard the value for TOM_EXAM_PAPER.SHOW_QUALIFIED_STANDARD
     *
     * @mbggenerated
     */
    public void setShowQualifiedStandard(String showQualifiedStandard) {
        this.showQualifiedStandard = showQualifiedStandard == null ? null : showQualifiedStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.IMMEDIATELY_SHOW
     *
     * @return the value of TOM_EXAM_PAPER.IMMEDIATELY_SHOW
     *
     * @mbggenerated
     */
    public String getImmediatelyShow() {
        return immediatelyShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.IMMEDIATELY_SHOW
     *
     * @param immediatelyShow the value for TOM_EXAM_PAPER.IMMEDIATELY_SHOW
     *
     * @mbggenerated
     */
    public void setImmediatelyShow(String immediatelyShow) {
        this.immediatelyShow = immediatelyShow == null ? null : immediatelyShow.trim();
    }

    

    public String getAdmins() {
		return admins;
	}

	public void setAdmins(String admins) {
		this.admins = admins;
	}

	public String getAdminNames() {
		return adminNames;
	}

	public void setAdminNames(String adminNames) {
		this.adminNames = adminNames;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.CREATE_TIME
     *
     * @return the value of TOM_EXAM_PAPER.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.CREATE_TIME
     *
     * @param createTime the value for TOM_EXAM_PAPER.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.CREATOR
     *
     * @return the value of TOM_EXAM_PAPER.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.CREATOR
     *
     * @param creator the value for TOM_EXAM_PAPER.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.LAST_OPERATOR
     *
     * @return the value of TOM_EXAM_PAPER.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public String getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.LAST_OPERATOR
     *
     * @param lastOperator the value for TOM_EXAM_PAPER.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public void setLastOperator(String lastOperator) {
        this.lastOperator = lastOperator == null ? null : lastOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_PAPER.UPDATE_TIME
     *
     * @return the value of TOM_EXAM_PAPER.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_PAPER.UPDATE_TIME
     *
     * @param updateTime the value for TOM_EXAM_PAPER.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public String getLastOperatorId() {
		return lastOperatorId;
	}

	public void setLastOperatorId(String lastOperatorId) {
		this.lastOperatorId = lastOperatorId;
	}

	public String getExamPaperNameEn() {
		return examPaperNameEn;
	}

	public void setExamPaperNameEn(String examPaperNameEn) {
		this.examPaperNameEn = examPaperNameEn;
	}
    private String sort;

	public String getSort() {
		return sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}
    
}