package com.chinamobo.ue.exam.entity;

import java.util.Date;

import javax.ws.rs.FormParam;

public class TomExamQuestion {
	
	@FormParam("questionBankName")
	private String questionBankName;
    public String getQuestionBankName() {
		return questionBankName;
	}

	public void setQuestionBankName(String questionBankName) {
		this.questionBankName = questionBankName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
	@FormParam("examPaperId")
    private Integer examPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
	@FormParam("questionBankId")
    private Integer questionBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.SORT
     *
     * @mbggenerated
     */
	@FormParam("sort")
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.QUESTION_TYPE
     *
     * @mbggenerated
     */
	@FormParam("questionType")
    private String questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.COUNT
     *
     * @mbggenerated
     */
	@FormParam("count")
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.SCORE
     *
     * @mbggenerated
     */
	@FormParam("score")
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_QUESTION.CREATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("createTime")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.EXAM_PAPER_ID
     *
     * @return the value of TOM_EXAM_QUESTION.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.EXAM_PAPER_ID
     *
     * @param examPaperId the value for TOM_EXAM_QUESTION.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.QUESTION_BANK_ID
     *
     * @return the value of TOM_EXAM_QUESTION.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
    public Integer getQuestionBankId() {
        return questionBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.QUESTION_BANK_ID
     *
     * @param questionBankId the value for TOM_EXAM_QUESTION.QUESTION_BANK_ID
     *
     * @mbggenerated
     */
    public void setQuestionBankId(Integer questionBankId) {
        this.questionBankId = questionBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.SORT
     *
     * @return the value of TOM_EXAM_QUESTION.SORT
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.SORT
     *
     * @param sort the value for TOM_EXAM_QUESTION.SORT
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.QUESTION_TYPE
     *
     * @return the value of TOM_EXAM_QUESTION.QUESTION_TYPE
     *
     * @mbggenerated
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.QUESTION_TYPE
     *
     * @param questionType the value for TOM_EXAM_QUESTION.QUESTION_TYPE
     *
     * @mbggenerated
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.COUNT
     *
     * @return the value of TOM_EXAM_QUESTION.COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.COUNT
     *
     * @param count the value for TOM_EXAM_QUESTION.COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.SCORE
     *
     * @return the value of TOM_EXAM_QUESTION.SCORE
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.SCORE
     *
     * @param score the value for TOM_EXAM_QUESTION.SCORE
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_QUESTION.CREATE_TIME
     *
     * @return the value of TOM_EXAM_QUESTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_QUESTION.CREATE_TIME
     *
     * @param createTime the value for TOM_EXAM_QUESTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}