package com.chinamobo.ue.exam.entity;

import java.util.Date;

public class TomExamTopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_TOPIC.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    private Integer examPaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    private Integer topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_EXAM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;
    
    private String sort;

    public String getSort() {
		return sort;
	}


	public void setSort(String sort) {
		this.sort = sort;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_TOPIC.EXAM_PAPER_ID
     *
     * @return the value of TOM_EXAM_TOPIC.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_TOPIC.EXAM_PAPER_ID
     *
     * @param examPaperId the value for TOM_EXAM_TOPIC.EXAM_PAPER_ID
     *
     * @mbggenerated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_TOPIC.TOPIC_ID
     *
     * @return the value of TOM_EXAM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_TOPIC.TOPIC_ID
     *
     * @param topicId the value for TOM_EXAM_TOPIC.TOPIC_ID
     *
     * @mbggenerated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_EXAM_TOPIC.CREATE_TIME
     *
     * @return the value of TOM_EXAM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_EXAM_TOPIC.CREATE_TIME
     *
     * @param createTime the value for TOM_EXAM_TOPIC.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}