package com.chinamobo.ue.exam.entity;

import java.util.Date;

import javax.ws.rs.FormParam;
import javax.xml.bind.annotation.XmlRootElement;

public class TomQuestionClassification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationId")
    private Integer questionClassificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationNumber")
    private String questionClassificationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationName")
    private String questionClassificationName;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationNameEn")
    private String questionClassificationNameEn;
	

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.PARENT_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
	@FormParam("parentClassificationId")
    private Integer parentClassificationId;
	
	@FormParam("parentClassificationName")
    private String parentClassificationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationAbstra")
    private String questionClassificationAbstra;
	
	
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @mbggenerated
     */
	@FormParam("questionClassificationAbstraEn")
    private String questionClassificationAbstraEn;
	

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.ADMIN_ID
     *
     * @mbggenerated
     */
	@FormParam("admins")
	private String admins;
	@FormParam("adminNames")
	private String adminNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
    private String creator;
	
	 private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.LAST_OPERATOR
     *
     * @mbggenerated
     */
	@FormParam("lastOperator")
    private String lastOperator;
	
	private String lastOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_QUESTION_CLASSIFICATION.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ID
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
    public Integer getQuestionClassificationId() {
        return questionClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ID
     *
     * @param questionClassificationId the value for TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
    public void setQuestionClassificationId(Integer questionClassificationId) {
        this.questionClassificationId = questionClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NUMBER
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NUMBER
     *
     * @mbggenerated
     */
    public String getQuestionClassificationNumber() {
        return questionClassificationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NUMBER
     *
     * @param questionClassificationNumber the value for TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NUMBER
     *
     * @mbggenerated
     */
    public void setQuestionClassificationNumber(String questionClassificationNumber) {
        this.questionClassificationNumber = questionClassificationNumber == null ? null : questionClassificationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @mbggenerated
     */
    public String getQuestionClassificationName() {
        return questionClassificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @param questionClassificationName the value for TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_NAME
     *
     * @mbggenerated
     */
    public void setQuestionClassificationName(String questionClassificationName) {
        this.questionClassificationName = questionClassificationName == null ? null : questionClassificationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.PARENT_CLASSIFICATION_ID
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.PARENT_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
    public Integer getParentClassificationId() {
        return parentClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.PARENT_CLASSIFICATION_ID
     *
     * @param parentClassificationId the value for TOM_QUESTION_CLASSIFICATION.PARENT_CLASSIFICATION_ID
     *
     * @mbggenerated
     */
    public void setParentClassificationId(Integer parentClassificationId) {
        this.parentClassificationId = parentClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @mbggenerated
     */
    public String getQuestionClassificationAbstra() {
        return questionClassificationAbstra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @param questionClassificationAbstra the value for TOM_QUESTION_CLASSIFICATION.QUESTION_CLASSIFICATION_ABSTRA
     *
     * @mbggenerated
     */
    public void setQuestionClassificationAbstra(String questionClassificationAbstra) {
        this.questionClassificationAbstra = questionClassificationAbstra == null ? null : questionClassificationAbstra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.CREATE_TIME
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.CREATE_TIME
     *
     * @param createTime the value for TOM_QUESTION_CLASSIFICATION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.CREATOR
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.CREATOR
     *
     * @param creator the value for TOM_QUESTION_CLASSIFICATION.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.LAST_OPERATOR
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public String getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.LAST_OPERATOR
     *
     * @param lastOperator the value for TOM_QUESTION_CLASSIFICATION.LAST_OPERATOR
     *
     * @mbggenerated
     */
    public void setLastOperator(String lastOperator) {
        this.lastOperator = lastOperator == null ? null : lastOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_QUESTION_CLASSIFICATION.UPDATE_TIME
     *
     * @return the value of TOM_QUESTION_CLASSIFICATION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_QUESTION_CLASSIFICATION.UPDATE_TIME
     *
     * @param updateTime the value for TOM_QUESTION_CLASSIFICATION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getAdmins() {
		return admins;
	}

	public void setAdmins(String admins) {
		this.admins = admins;
	}

	public String getAdminNames() {
		return adminNames;
	}

	public void setAdminNames(String adminNames) {
		this.adminNames = adminNames;
	}

	public String getParentClassificationName() {
		return parentClassificationName;
	}

	public void setParentClassificationName(String parentClassificationName) {
		this.parentClassificationName = parentClassificationName;
	}

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public String getLastOperatorId() {
		return lastOperatorId;
	}

	public void setLastOperatorId(String lastOperatorId) {
		this.lastOperatorId = lastOperatorId;
	}

	public String getQuestionClassificationNameEn() {
		return questionClassificationNameEn;
	}

	public void setQuestionClassificationNameEn(String questionClassificationNameEn) {
		this.questionClassificationNameEn = questionClassificationNameEn;
	}

	public String getQuestionClassificationAbstraEn() {
		return questionClassificationAbstraEn;
	}

	public void setQuestionClassificationAbstraEn(String questionClassificationAbstraEn) {
		this.questionClassificationAbstraEn = questionClassificationAbstraEn;
	}
	
	
	

    
}