package com.chinamobo.ue.exam.entity;

import java.util.Date;

public class TomRetakingExam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_RETAKING_EXAM.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_RETAKING_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
    private Integer examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_RETAKING_EXAM.SORT
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_RETAKING_EXAM.RETAKING_EXAM_BEGIN_TIME
     *
     * @mbggenerated
     */
    private Date retakingExamBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_RETAKING_EXAM.RETAKING_EXAM_END_TIME
     *
     * @mbggenerated
     */
    private Date retakingExamEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_RETAKING_EXAM.ID
     *
     * @return the value of TOM_RETAKING_EXAM.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_RETAKING_EXAM.ID
     *
     * @param id the value for TOM_RETAKING_EXAM.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_RETAKING_EXAM.EXAM_ID
     *
     * @return the value of TOM_RETAKING_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_RETAKING_EXAM.EXAM_ID
     *
     * @param examId the value for TOM_RETAKING_EXAM.EXAM_ID
     *
     * @mbggenerated
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_RETAKING_EXAM.SORT
     *
     * @return the value of TOM_RETAKING_EXAM.SORT
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_RETAKING_EXAM.SORT
     *
     * @param sort the value for TOM_RETAKING_EXAM.SORT
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_RETAKING_EXAM.RETAKING_EXAM_BEGIN_TIME
     *
     * @return the value of TOM_RETAKING_EXAM.RETAKING_EXAM_BEGIN_TIME
     *
     * @mbggenerated
     */
    public Date getRetakingExamBeginTime() {
        return retakingExamBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_RETAKING_EXAM.RETAKING_EXAM_BEGIN_TIME
     *
     * @param retakingExamBeginTime the value for TOM_RETAKING_EXAM.RETAKING_EXAM_BEGIN_TIME
     *
     * @mbggenerated
     */
    public void setRetakingExamBeginTime(Date retakingExamBeginTime) {
        this.retakingExamBeginTime = retakingExamBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_RETAKING_EXAM.RETAKING_EXAM_END_TIME
     *
     * @return the value of TOM_RETAKING_EXAM.RETAKING_EXAM_END_TIME
     *
     * @mbggenerated
     */
    public Date getRetakingExamEndTime() {
        return retakingExamEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_RETAKING_EXAM.RETAKING_EXAM_END_TIME
     *
     * @param retakingExamEndTime the value for TOM_RETAKING_EXAM.RETAKING_EXAM_END_TIME
     *
     * @mbggenerated
     */
    public void setRetakingExamEndTime(Date retakingExamEndTime) {
        this.retakingExamEndTime = retakingExamEndTime;
    }
}