package com.chinamobo.ue.course.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.course.entity.TomCourseComment;
import com.chinamobo.ue.course.entity.TomCourseCommentThumbUp;
import com.chinamobo.ue.course.entity.TomGradeDimension;

public interface TomCourseCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer courseCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    int insert(TomCourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    int insertSelective(TomCourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    TomCourseComment selectByPrimaryKey(Integer courseCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomCourseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_COMMENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomCourseComment record);
    
    
    /**
     * 功能描述：[查询讲师/课程维度]
     *
     * 创建者：WangLg
     * 创建时间: 2016年3月2日 下午1:30:33
     * @param record
     * @return
     */
    List<TomGradeDimension> findGradeDimenComList(TomGradeDimension record); 
    
    /**
     * 功能描述：[修改讲师评分/课程评分]
     *
     * 创建者：WangLg
     * 创建时间: 2016年3月2日 下午1:31:27
     * @param record
     */
    void updateGradeDimByType(TomGradeDimension record);

    /**
     * 
     * 功能描述：[分页查询课程评论]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月15日 下午2:54:27
     * @param pageNum
     * @param pageSize
     * @param courseId 
     * @return
     */
	List<TomCourseComment> selectListByPage(Map<Object, Object> map);

	/**
	 * 
	 * 功能描述：[根据课程id查询课程评论总数]
	 *
	 * 创建者：JCX
	 * 创建时间: 2016年3月15日 下午3:00:31
	 * @param example
	 * @return
	 */
	int countByExample(TomCourseComment example);
	
	/**
	 * 
	 * 功能描述：课程评论点赞 
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月22日上午10:57:16
	 * @param example
	 */
	void insertThumbUp(TomCourseCommentThumbUp example);
	
	/**
	 * 
	 * 功能描述：更新点赞状态
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月22日上午11:00:50
	 * @param example
	 */
	void updateThumbUpByCourseIdandCode(TomCourseCommentThumbUp example);
	
	/**
	 * 
	 * 功能描述：查看是否已经点赞
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月22日上午11:05:15
	 * @param example
	 * @return
	 */
	int countThumbUpByCourseIdAndCode(TomCourseCommentThumbUp example);
	
	/**
	 * 
	 * 功能描述：查看已点赞信息
	 *
	 * 创建者：ZXM
	 * 创建时间: 2016年3月22日上午11:07:08
	 * @param example
	 * @return
	 */
	TomCourseCommentThumbUp selectThumbUpByCourseIdAndCode(TomCourseCommentThumbUp example);
	/**
	 * 根据courseId查评论内容
	 */
	TomCourseComment selectByCourseId(int courseId);


}