package com.chinamobo.ue.course.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.chinamobo.ue.api.qcloud.dto.qcloudResult;
import com.chinamobo.ue.course.entity.TomCourseSection;
import com.chinamobo.ue.course.entity.TomCourseSectionLearningRecord;

public interface TomCourseSectionMapper {

    /**
     * 
     * 功能描述：[查询章节]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月31日 下午2:00:28
     * @param example
     * @return
     */
	List<TomCourseSection> selectListByExample(TomCourseSection example);

	List<TomCourseSection> selectListByCourseId(Integer courseId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    int insert(TomCourseSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    int insertSelective(TomCourseSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    TomCourseSection selectByPrimaryKey(Integer sectionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomCourseSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_COURSE_SECTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomCourseSection record);

	 /**
     * 
     * 功能描述：分页查询章节数据
     *
     * 创建者：ZXM
     * 创建时间: 2016年3月23日上午11:14:42
     * @param map
     * @return
     */
    List<TomCourseSection> selectListByPage(Map<Object, Object> map);
    
    /**
     * 
     * 功能描述：根据课程id与状态查询章节数量
     *
     * 创建者：ZXM
     * 创建时间: 2016年3月23日上午11:15:10
     * @param example
     * @return
     */
    int countByExample(TomCourseSection example);
    
    /**
     * 
     * 功能描述：查询课程章节学习关联数据
     *
     * 创建者：ZXM
     * 创建时间: 2016年3月23日下午2:47:23
     * @param example
     * @return
     */
    int countByCodeAndSectionId(TomCourseSectionLearningRecord example);
    /**
     * 功能描述：查询课程章节视频存放地址
     * 
     * 创建者：LG
     * 创建时间：2016年6月1日下午2：02：30
     * 
     */
    qcloudResult selectBySectionId(Map<Object,Object> map);

    /**
     * 
     * 功能描述：[根据课程id删除课程章节]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月12日 下午1:06:23
     * @param courseId
     */
	//void deleteByCourseId(Integer courseId);
    /**
     * 
     * 功能描述：[根据课程id与章节序号查询课程章节]
     *
     * 创建者：JCX
     * 创建时间: 2016年4月12日 下午1:06:23
     * @param courseId
     */
    List<TomCourseSection> selectBySort(Map<Object,Object> map);
    
    int countByDriver(Map<Object,Object> map);
    List<TomCourseSection> pageByDriver(Map<Object,Object> map);

}
