package com.chinamobo.ue.course.dao;

import java.util.List;
import java.util.Map;

import com.chinamobo.ue.course.entity.TomLecturer;

public interface TomLecturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer lecturerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    int insert(TomLecturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    int insertSelective(TomLecturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    TomLecturer selectByPrimaryKey(Integer lecturerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TomLecturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOM_LECTURE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TomLecturer record);
    
    /**
     * 
     * 功能描述：[按条件分页查询]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月1日 上午9:57:45
     * @param map
     * @return
     */
    List<TomLecturer> selectListByPage(Map<Object,Object> map);
    
    /**
     * 
     * 功能描述：[统计条件查询结果]
     *
     * 创建者：JCX
     * 创建时间: 2016年3月1日 上午9:57:58
     * @param example
     * @return
     */
    int countByExample(TomLecturer example);

	List<TomLecturer> selectAll(TomLecturer example);
	
	
	/**
	 * 功能描述：[选择讲师]
	 *
	 * 创建者：WangLg
	 * 创建时间: 2016年3月15日 下午2:54:07
	 * @return
	 */
	List<TomLecturer> selectAllName();
	
	TomLecturer selectByCode(String code);

	Double selectLecturerAvg(Integer lecturerId);
	
}