package com.chinamobo.ue.course.entity;

import java.util.Date;

import javax.ws.rs.FormParam;
import javax.ws.rs.PathParam;

public class TomCourseComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.COURSE_COMMENT_ID
     *
     * @mbggenerated
     */
	@FormParam("courseCommentId")
    private Integer courseCommentId;
	@FormParam("anonymity")
    private String anonymity;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.COURSE_ID
     *
     * @mbggenerated
     */
	@FormParam("courseId")
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.CODE
     *
     * @mbggenerated
     */
	@FormParam("code")
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.NAME
     *
     * @mbggenerated
     */
	@FormParam("name")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.THUMB_UP_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("thumbUpNumber")
    private Integer thumbUpNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.COURSE_COMMENT_CONTENT
     *
     * @mbggenerated
     */
	@FormParam("courseCommentContent")
    private String courseCommentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
	@FormParam("createTime")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_COMMENT.STATUS
     *
     * @mbggenerated
     */
	@FormParam("status")
    private String status;

	@FormParam("btnString")
    private String btnString;
	
	private String headImg;//用户头像
	
	private String praise;//点赞状态
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.COURSE_COMMENT_ID
     *
     * @return the value of TOM_COURSE_COMMENT.COURSE_COMMENT_ID
     *
     * @mbggenerated
     */
    public Integer getCourseCommentId() {
        return courseCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.COURSE_COMMENT_ID
     *
     * @param courseCommentId the value for TOM_COURSE_COMMENT.COURSE_COMMENT_ID
     *
     * @mbggenerated
     */
    public void setCourseCommentId(Integer courseCommentId) {
        this.courseCommentId = courseCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.COURSE_ID
     *
     * @return the value of TOM_COURSE_COMMENT.COURSE_ID
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.COURSE_ID
     *
     * @param courseId the value for TOM_COURSE_COMMENT.COURSE_ID
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.CODE
     *
     * @return the value of TOM_COURSE_COMMENT.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.CODE
     *
     * @param code the value for TOM_COURSE_COMMENT.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.NAME
     *
     * @return the value of TOM_COURSE_COMMENT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.NAME
     *
     * @param name the value for TOM_COURSE_COMMENT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.THUMB_UP_NUMBER
     *
     * @return the value of TOM_COURSE_COMMENT.THUMB_UP_NUMBER
     *
     * @mbggenerated
     */
    public Integer getThumbUpNumber() {
        return thumbUpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.THUMB_UP_NUMBER
     *
     * @param thumbUpNumber the value for TOM_COURSE_COMMENT.THUMB_UP_NUMBER
     *
     * @mbggenerated
     */
    public void setThumbUpNumber(Integer thumbUpNumber) {
        this.thumbUpNumber = thumbUpNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.COURSE_COMMENT_CONTENT
     *
     * @return the value of TOM_COURSE_COMMENT.COURSE_COMMENT_CONTENT
     *
     * @mbggenerated
     */
    public String getCourseCommentContent() {
        return courseCommentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.COURSE_COMMENT_CONTENT
     *
     * @param courseCommentContent the value for TOM_COURSE_COMMENT.COURSE_COMMENT_CONTENT
     *
     * @mbggenerated
     */
    public void setCourseCommentContent(String courseCommentContent) {
        this.courseCommentContent = courseCommentContent == null ? null : courseCommentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.CREATE_TIME
     *
     * @return the value of TOM_COURSE_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.CREATE_TIME
     *
     * @param createTime the value for TOM_COURSE_COMMENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_COMMENT.STATUS
     *
     * @return the value of TOM_COURSE_COMMENT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_COMMENT.STATUS
     *
     * @param status the value for TOM_COURSE_COMMENT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

	public String getBtnString() {
		if(status.equals("Y")){
			return "禁用";
		}else{
			return "开启";
		}
	}

	public void setBtnString(String btnString) {
		this.btnString = btnString;
	}

	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getPraise() {
		return praise;
	}

	public void setPraise(String praise) {
		this.praise = praise;
	}

	public String getAnonymity() {
		return anonymity;
	}

	public void setAnonymity(String anonymity) {
		this.anonymity = anonymity;
	}

	
}