package com.chinamobo.ue.course.entity;

import java.util.Date;

public class TomCourseSection {
	
	private String systemType;
	
    public String getSystemType() {
		return systemType;
	}

	public void setSystemType(String systemType) {
		this.systemType = systemType;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.SECTION_ID
     *
     * @mbggenerated
     */
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.COURSE_ID
     *
     * @mbggenerated
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.SECTION_ADDRESS
     *
     * @mbggenerated
     */
    private String sectionAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.SECTION_NAME
     *
     * @mbggenerated
     */
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.SECTION_TYPE
     *
     * @mbggenerated
     */
    private String sectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.CREATOR
     *
     * @mbggenerated
     */
    private String creator;
    
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_COURSE_SECTION.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;
    
    private String courseFileuploadAddress;//课程内容
    
    private String learningStates;//学习状态

    private Integer sectionSize;
    
    private String fileUrl;
    
    private String sectionNameEn;
    private Integer sectionSort;
    private String lang;
    private String tid;
    private String cid;
    private String sig;
    private String corpid;
    
    
    public Integer getSectionSort() {
		return sectionSort;
	}

	public void setSectionSort(Integer sectionSort) {
		this.sectionSort = sectionSort;
	}

	public String getCorpid() {
		return corpid;
	}

	public void setCorpid(String corpid) {
		this.corpid = corpid;
	}

	public String getSig() {
		return sig;
	}

	public void setSig(String sig) {
		this.sig = sig;
	}

	public String getTid() {
		return tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	public String getCid() {
		return cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getSectionNameEn() {
		return sectionNameEn;
	}

	public void setSectionNameEn(String sectionNameEn) {
		this.sectionNameEn = sectionNameEn;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getFileUrl() {
		return fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.SECTION_ID
     *
     * @return the value of TOM_COURSE_SECTION.SECTION_ID
     *
     * @mbggenerated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.SECTION_ID
     *
     * @param sectionId the value for TOM_COURSE_SECTION.SECTION_ID
     *
     * @mbggenerated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.COURSE_ID
     *
     * @return the value of TOM_COURSE_SECTION.COURSE_ID
     *
     * @mbggenerated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.COURSE_ID
     *
     * @param courseId the value for TOM_COURSE_SECTION.COURSE_ID
     *
     * @mbggenerated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.SECTION_ADDRESS
     *
     * @return the value of TOM_COURSE_SECTION.SECTION_ADDRESS
     *
     * @mbggenerated
     */
    public String getSectionAddress() {
        return sectionAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.SECTION_ADDRESS
     *
     * @param sectionAddress the value for TOM_COURSE_SECTION.SECTION_ADDRESS
     *
     * @mbggenerated
     */
    public void setSectionAddress(String sectionAddress) {
        this.sectionAddress = sectionAddress == null ? null : sectionAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.SECTION_NAME
     *
     * @return the value of TOM_COURSE_SECTION.SECTION_NAME
     *
     * @mbggenerated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.SECTION_NAME
     *
     * @param sectionName the value for TOM_COURSE_SECTION.SECTION_NAME
     *
     * @mbggenerated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.SECTION_TYPE
     *
     * @return the value of TOM_COURSE_SECTION.SECTION_TYPE
     *
     * @mbggenerated
     */
    public String getSectionType() {
        return sectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.SECTION_TYPE
     *
     * @param sectionType the value for TOM_COURSE_SECTION.SECTION_TYPE
     *
     * @mbggenerated
     */
    public void setSectionType(String sectionType) {
        this.sectionType = sectionType == null ? null : sectionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.STATUS
     *
     * @return the value of TOM_COURSE_SECTION.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.STATUS
     *
     * @param status the value for TOM_COURSE_SECTION.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.CREATOR
     *
     * @return the value of TOM_COURSE_SECTION.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.CREATOR
     *
     * @param creator the value for TOM_COURSE_SECTION.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.CREATE_TIME
     *
     * @return the value of TOM_COURSE_SECTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.CREATE_TIME
     *
     * @param createTime the value for TOM_COURSE_SECTION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.OPERATOR
     *
     * @return the value of TOM_COURSE_SECTION.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.OPERATOR
     *
     * @param operator the value for TOM_COURSE_SECTION.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_COURSE_SECTION.UPDATE_TIME
     *
     * @return the value of TOM_COURSE_SECTION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_COURSE_SECTION.UPDATE_TIME
     *
     * @param updateTime the value for TOM_COURSE_SECTION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getCourseFileuploadAddress() {
		return courseFileuploadAddress;
	}

	public void setCourseFileuploadAddress(String courseFileuploadAddress) {
		this.courseFileuploadAddress = courseFileuploadAddress;
	}

	public String getLearningStates() {
		return learningStates;
	}

	public void setLearningStates(String learningStates) {
		this.learningStates = learningStates;
	}

	public Integer getSectionSize() {
		return sectionSize;
	}

	public void setSectionSize(Integer sectionSize) {
		this.sectionSize = sectionSize;
	}

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}
    
    
}