package com.chinamobo.ue.course.entity;

import java.util.Date;
import java.util.List;

import javax.ws.rs.FormParam;

import org.springframework.beans.factory.annotation.Autowired;

import com.chinamobo.ue.system.service.NumberRecordService;
import com.chinamobo.ue.ums.util.ShiroUtils;
import com.chinamobo.ue.utils.Global;
import com.chinamobo.ue.utils.MapManager;
import com.google.common.collect.Lists;

public class TomGradeDimension {//extends DataEntity<TomGradeDimension>{
	
  	@FormParam("gradeDeimensionType")
  	private String gradeDeimensionType;
      
	public String getGradeDeimensionType() {
		return gradeDeimensionType;
	}

	public void setGradeDeimensionType(String gradeDeimensionType) {
		this.gradeDeimensionType = gradeDeimensionType;
	}

	@FormParam("gradeType")
	private String gradeType;
	
    public String getGradeType() {
		return gradeType;
	}

	public void setGradeType(String gradeType) {
		this.gradeType = gradeType;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_ID
     *
     * @mbggenerated
     */
	@FormParam("gradeDimensionId")
    private Integer gradeDimensionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NUMBER
     *
     * @mbggenerated
     */
	@FormParam("gradeDimensionNumber")
    private String gradeDimensionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @mbggenerated
     */
	@FormParam("gradeDimensionName")
    private String gradeDimensionName;
	
	
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @mbggenerated
     */
	@FormParam("gradeDimensionNameEn")
    private String gradeDimensionNameEn;
	

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_TYPE
     *
     * @mbggenerated
     */
	@FormParam("gradeDimensionType")
    private String gradeDimensionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.STATUS
     *
     * @mbggenerated
     */
	@FormParam("status")
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.CREATOR
     *
     * @mbggenerated
     */
	@FormParam("creator")
    private String creator;
	
	private String creatorId;
	
	

    public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    private String operatorId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_GRADE_DIMENSION.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;
    
	@Autowired
	private NumberRecordService numberRecordService;
    /**
	 * 插入前调用
	 */
//	public void preInsert(){
//	
//		String user  = ShiroUtils.getCurrentUser().getName();
//		this.operator = user;
//		this.creator = user;
//		this.updateTime = new Date();
//		this.createTime = new Date();
//		this.status = Global.YES;
//		if(this.gradeDimensionType.equals("C")){
//			this.gradeDimensionNumber = numberRecordService.getNumber(MapManager.numberType(Global.CKPF));
//		}
//		this.gradeDimensionNumber = numberRecordService.getNumber(MapManager.numberType(Global.JSPF));
//	}
	
	/**
	 * 插入后调用
	 */
	public void preUpdate(){
		String user  = ShiroUtils.getCurrentUser().getName();
		this.operator = user;
		this.updateTime = new Date();
		this.status = Global.YES;
	}
	
	
	/**
	 * 删除调用
	 */
	public void preDelete(){
		String user  = ShiroUtils.getCurrentUser().getName();
		this.operator = user;
		this.updateTime = new Date();
		this.status = Global.NO;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_ID
     *
     * @return the value of TOM_GRADE_DIMENSION.GRADE_DIMENSION_ID
     *
     * @mbggenerated
     */
    public Integer getGradeDimensionId() {
        return gradeDimensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_ID
     *
     * @param gradeDimensionId the value for TOM_GRADE_DIMENSION.GRADE_DIMENSION_ID
     *
     * @mbggenerated
     */
    public void setGradeDimensionId(Integer gradeDimensionId) {
        this.gradeDimensionId = gradeDimensionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NUMBER
     *
     * @return the value of TOM_GRADE_DIMENSION.GRADE_DIMENSION_NUMBER
     *
     * @mbggenerated
     */
    public String getGradeDimensionNumber() {
        return gradeDimensionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NUMBER
     *
     * @param gradeDimensionNumber the value for TOM_GRADE_DIMENSION.GRADE_DIMENSION_NUMBER
     *
     * @mbggenerated
     */
    public void setGradeDimensionNumber(String gradeDimensionNumber) {
        this.gradeDimensionNumber = gradeDimensionNumber == null ? null : gradeDimensionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @return the value of TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @mbggenerated
     */
    public String getGradeDimensionName() {
        return gradeDimensionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @param gradeDimensionName the value for TOM_GRADE_DIMENSION.GRADE_DIMENSION_NAME
     *
     * @mbggenerated
     */
    public void setGradeDimensionName(String gradeDimensionName) {
        this.gradeDimensionName = gradeDimensionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_TYPE
     *
     * @return the value of TOM_GRADE_DIMENSION.GRADE_DIMENSION_TYPE
     *
     * @mbggenerated
     */
    public String getGradeDimensionType() {
        return gradeDimensionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.GRADE_DIMENSION_TYPE
     *
     * @param gradeDimensionType the value for TOM_GRADE_DIMENSION.GRADE_DIMENSION_TYPE
     *
     * @mbggenerated
     */
    public void setGradeDimensionType(String gradeDimensionType) {
        this.gradeDimensionType = gradeDimensionType == null ? null : gradeDimensionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.STATUS
     *
     * @return the value of TOM_GRADE_DIMENSION.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.STATUS
     *
     * @param status the value for TOM_GRADE_DIMENSION.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.CREATOR
     *
     * @return the value of TOM_GRADE_DIMENSION.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.CREATOR
     *
     * @param creator the value for TOM_GRADE_DIMENSION.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.CREATE_TIME
     *
     * @return the value of TOM_GRADE_DIMENSION.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.CREATE_TIME
     *
     * @param createTime the value for TOM_GRADE_DIMENSION.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.OPERATOR
     *
     * @return the value of TOM_GRADE_DIMENSION.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.OPERATOR
     *
     * @param operator the value for TOM_GRADE_DIMENSION.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_GRADE_DIMENSION.UPDATE_TIME
     *
     * @return the value of TOM_GRADE_DIMENSION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOM_GRADE_DIMENSION.UPDATE_TIME
     *
     * @param updateTime the value for TOM_GRADE_DIMENSION.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public String getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	public String getGradeDimensionNameEn() {
		return gradeDimensionNameEn;
	}

	public void setGradeDimensionNameEn(String gradeDimensionNameEn) {
		this.gradeDimensionNameEn = gradeDimensionNameEn;
	}
	
	
    
    
}