package com.chinamobo.ue.activity.dto;

import java.util.Date;

import javax.ws.rs.FormParam;

import com.chinamobo.ue.activity.entity.TomActivity;
import com.chinamobo.ue.activity.entity.TomActivityEmpsRelationKey;
import com.chinamobo.ue.system.entity.TomEmp;
import com.chinamobo.ue.utils.Global;

public class TomActivityProcessDto extends TomActivityEmpsRelationKey{
	
	private String activityProcess;
	private Integer totalTask;
	private Integer finishedCourseTask;
	private Integer finishedExamTask;
	private String secretEmail;
	private String deptname;
	private String jobname;
	private String mobile;
	
	public String getActivityProcess() {
		return activityProcess;
	}

	public void setActivityProcess(String activityProcess) {
		this.activityProcess = activityProcess;
	}

	public double getTotalTask() {
		return totalTask;
	}

	

	public Integer getFinishedCourseTask() {
		return finishedCourseTask;
	}

	public void setFinishedCourseTask(Integer finishedCourseTask) {
		this.finishedCourseTask = finishedCourseTask;
	}

	public Integer getFinishedExamTask() {
		return finishedExamTask;
	}

	public void setFinishedExamTask(Integer finishedExamTask) {
		this.finishedExamTask = finishedExamTask;
	}

	public void setTotalTask(Integer totalTask) {
		this.totalTask = totalTask;
	}

	public TomActivityProcessDto() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.STATUS
	 *
	 * @mbggenerated
	 */
	@FormParam("status")
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_STATUS
	 *
	 * @mbggenerated
	 */
	@FormParam("applyStatus")
	private String applyStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_TYPE
	 *
	 * @mbggenerated
	 */
	@FormParam("applyType")
	private String applyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.IS_REQUIRED
	 *
	 * @mbggenerated
	 */
	@FormParam("isRequired")
	private String isRequired;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.CREATOR
	 *
	 * @mbggenerated
	 */
	@FormParam("creator")
	private String creator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("createTime")
	private Date createTime;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.OPERATOR
	 *
	 * @mbggenerated
	 */
	@FormParam("operator")
	private String operator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column TOM_ACTIVITY_EMPS_RELATION.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	@FormParam("updateTime")
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.STATUS
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.STATUS
	 *
	 * @mbggenerated
	 */
	@FormParam("tomEmp")
	private TomEmp tomEmp;

	@FormParam("tomActivity")
	private TomActivity tomActivity;
	

	/**
	 * 插入前调用
	 */
	public void preInsertData(){
	
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.creator = user;
//		this.updateTime = new Date();
//		this.createTime = new Date();
		this.status = Global.GL;//Y 正常  N 取消关联
		this.applyStatus = Global.YBM;
		this.applyType = "E";//员工自行报名
//		if("D".equals(applyType)){
//			this.applyType = "D";//负责人报名
//		}else{
//			this.applyType = "E";//员工自行报名
//		}
	}
	
	/**
	 * 插入后调用
	 */
	public void preUpdateData(){
		//String user  = ShiroUtils.getCurrentUser().getName();
//		String user  = "4";
//		this.operator = user;
//		this.updateTime = new Date();
	}
	/*
	 * 取消关联
	 */
	public void preUpdateStatusData(){
		this.applyStatus = Global.WBM;
		this.status = Global.QXGL;
	}
	

	public TomEmp getTomEmp() {
		return tomEmp;
	}

	public void setTomEmp(TomEmp tomEmp) {
		this.tomEmp = tomEmp;
	}

	public TomActivity getTomActivity() {
		return tomActivity;
	}

	public void setTomActivity(TomActivity tomActivity) {
		this.tomActivity = tomActivity;
	}

	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.STATUS
	 *
	 * @param status
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_STATUS
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.APPLY_STATUS
	 *
	 * @mbggenerated
	 */
	public String getApplyStatus() {
		return applyStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_STATUS
	 *
	 * @param applyStatus
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.APPLY_STATUS
	 *
	 * @mbggenerated
	 */
	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus == null ? null : applyStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_TYPE
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.APPLY_TYPE
	 *
	 * @mbggenerated
	 */
	public String getApplyType() {
		return applyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.APPLY_TYPE
	 *
	 * @param applyType
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.APPLY_TYPE
	 *
	 * @mbggenerated
	 */
	public void setApplyType(String applyType) {
		this.applyType = applyType == null ? null : applyType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.IS_REQUIRED
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.IS_REQUIRED
	 *
	 * @mbggenerated
	 */
	public String getIsRequired() {
		return isRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.IS_REQUIRED
	 *
	 * @param isRequired
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.IS_REQUIRED
	 *
	 * @mbggenerated
	 */
	public void setIsRequired(String isRequired) {
		this.isRequired = isRequired == null ? null : isRequired.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.CREATOR
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.CREATOR
	 *
	 * @mbggenerated
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.CREATOR
	 *
	 * @param creator
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.CREATOR
	 *
	 * @mbggenerated
	 */
	public void setCreator(String creator) {
		this.creator = creator == null ? null : creator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.CREATE_TIME
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.CREATE_TIME
	 *
	 * @param createTime
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.OPERATOR
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.OPERATOR
	 *
	 * @mbggenerated
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.OPERATOR
	 *
	 * @param operator
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.OPERATOR
	 *
	 * @mbggenerated
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.UPDATE_TIME
	 *
	 * @return the value of TOM_ACTIVITY_EMPS_RELATION.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column TOM_ACTIVITY_EMPS_RELATION.UPDATE_TIME
	 *
	 * @param updateTime
	 *            the value for TOM_ACTIVITY_EMPS_RELATION.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getSecretEmail() {
		return secretEmail;
	}

	public void setSecretEmail(String secretEmail) {
		this.secretEmail = secretEmail;
	}

	public String getDeptname() {
		return deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getJobname() {
		return jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	
	
	

}
