package com.chinamobo.ue.api.message.dto;

import java.util.Date;

import javax.ws.rs.FormParam;

public class MessageDto {
	@FormParam("messageId")
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.MESSAGE_TITLE
     *
     * @mbggenerated
     */
	@FormParam("messageTitle")
    private String messageTitle;
	
	@FormParam("messageTitleEn")
    private String messageTitleEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.CREATE_TIME
     *
     * @mbggenerated
     */
	
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.VIEW_COUNT
     *
     * @mbggenerated
     */
	@FormParam("viewCount")
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.MESSAGE_DETAILS
     *
     * @mbggenerated
     */
	@FormParam("messageDetails")
    private String messageDetails;
	
	@FormParam("messageDetailsEn")
    private String messageDetailsEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.MESSAGE_TYPE
     *
     * @mbggenerated
     */
	@FormParam("messageType")
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.SEND_TO_APP
     *
     * @mbggenerated
     */
	@FormParam("sendToApp")
    private String sendToApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.SEND_TO_EMAIL
     *
     * @mbggenerated
     */
	@FormParam("sendToEmail")
    private String sendToEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOM_MESSAGES.SEND_TO_PHONE
     *
     * @mbggenerated
     */
	@FormParam("sendToPhone")
    private String sendToPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOM_MESSAGES.MESSAGE_ID
     *
     * @return the value of TOM_MESSAGES.MESSAGE_ID
     *
     * @mbggenerated
     */
	private String org;
	private String dept;
	
	private String isView;
	private String pcUrl;
	
	public String getPcUrl() {
		return pcUrl;
	}

	public void setPcUrl(String pcUrl) {
		this.pcUrl = pcUrl;
	}

	public String getAppUrl() {
		return appUrl;
	}

	public void setAppUrl(String appUrl) {
		this.appUrl = appUrl;
	}
	private String appUrl;
	
	public String getIsView() {
		return isView;
	}
	public void setIsView(String isView) {
		this.isView = isView;
	}
	public Integer getMessageId() {
		return messageId;
	}
	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}
	public String getMessageTitle() {
		return messageTitle;
	}
	public void setMessageTitle(String messageTitle) {
		this.messageTitle = messageTitle;
	}
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	public Integer getViewCount() {
		return viewCount;
	}
	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}
	public String getMessageDetails() {
		return messageDetails;
	}
	public void setMessageDetails(String messageDetails) {
		this.messageDetails = messageDetails;
	}
	public String getMessageType() {
		return messageType;
	}
	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}
	public String getSendToApp() {
		return sendToApp;
	}
	public void setSendToApp(String sendToApp) {
		this.sendToApp = sendToApp;
	}
	public String getSendToEmail() {
		return sendToEmail;
	}
	public void setSendToEmail(String sendToEmail) {
		this.sendToEmail = sendToEmail;
	}
	public String getSendToPhone() {
		return sendToPhone;
	}
	public void setSendToPhone(String sendToPhone) {
		this.sendToPhone = sendToPhone;
	}
	public String getOrg() {
		return org;
	}
	public void setOrg(String org) {
		this.org = org;
	}
	public String getDept() {
		return dept;
	}
	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getMessageTitleEn() {
		return messageTitleEn;
	}

	public void setMessageTitleEn(String messageTitleEn) {
		this.messageTitleEn = messageTitleEn;
	}

	public String getMessageDetailsEn() {
		return messageDetailsEn;
	}

	public void setMessageDetailsEn(String messageDetailsEn) {
		this.messageDetailsEn = messageDetailsEn;
	}

}
